export const SACCADIC_GALLERY_I18N = {
  en: { saccadicGallery: {
    title: 'Saccadic Eye Exercises', subtitle: 'Rapid Gaze Shifts • Visual Acquisition', caption: 'Shift your gaze between targets quickly and click each one with precision.',
    score: 'Score', time: 'Time', timeLeft: 'Time Left', level: 'Level', bestScore: 'Best Score',
    rotateLandscape: 'Rotate to landscape mode for a wider visual sweep field.', toggleMissFlash: 'Toggle Miss Flash', toggleSound: 'Toggle Sound', getReady: 'GET READY',
    rulesTitle: 'Drill Instructions & Scoring System', rule1Text: 'Hit Active Nodes', rule1Highlight: '+100 PTS', rule1Result: '× Combo × Level bonus (+0.6s clock per hit)', rule2Text: 'Combo & Heat System', rule2Highlight: 'Up to 3.0x Multiplier', rule2Result: 'Higher streaks speed up node jump cadence', rule3Text: 'Level Progression', rule3Highlight: 'Continuous Scaling', rule3Result: 'Targets shrink and exposure windows shorten', rule4Text: 'Miss & Timeout Rules', rule4HighlightPenalty: '-0.8s Penalty', rule4HighlightZero: 'Zero Penalties (Default)', rule4ResultPenalty: 'Deducts 0.8s & resets combo', rule4ResultZero: 'Resets combo. Time penalty is opt-in via settings',
    aboutTitle: 'About Saccadic Gallery', aboutHeading: 'What Is Saccadic Eye Movement & Gallery Training?', aboutP1: 'Saccadic Gallery trains rapid eye movements between fixation points. In competitive games, saccadic speed influences how quickly your gaze reaches targets across different screen regions.', aboutP2: 'Repeatedly shifting focus across timed nodes develops visual acquisition and hand-eye coordination without claiming to diagnose or treat an eye condition.', audienceTitle: 'Who Should Use This?', audienceDesc: 'Gamers and esports athletes sharpening rapid gaze acquisition, visual scanning, and first-shot accuracy.', calibrationTitle: 'Saccadic Gaze Calibration', calibrationDesc: 'Practise controlled gaze shifts across screen sectors while keeping each fixation brief and accurate.', acquisitionTitle: 'Rapid Target Acquisition', acquisitionDesc: 'Build faster visual-to-motor timing when a new target appears.',
    accuracy: 'Accuracy', avgReaction: 'Avg Reaction', peakLevel: 'Peak Level', maxCombo: 'Max Combo',
    scoreShareTitle: 'Saccadic Gallery — My Score', scoreShareText: 'I scored {score} (Grade: {grade}, Lv. {level}) on Saccadic Gallery at SkillDrills!', scoreShareTitleShort: 'Saccadic Gallery', scoreShareTextShort: 'I scored {score} on Saccadic Gallery! Can you beat my score?'
  } },
  pt: { saccadicGallery: {
    title: 'Exercícios Sacádicos', subtitle: 'Saltos do Olhar • Aquisição Visual', caption: 'Mude o olhar rapidamente entre os alvos e clique em cada um com precisão.',
    score: 'Pontos', time: 'Tempo', timeLeft: 'Tempo Restante', level: 'Nível', bestScore: 'Recorde', rotateLandscape: 'Gire para o modo paisagem para ampliar o campo de varredura visual.', toggleMissFlash: 'Ativar/desativar flash de erro', toggleSound: 'Ativar/desativar som', getReady: 'PREPARE-SE',
    rulesTitle: 'Instruções do Treino e Pontuação', rule1Text: 'Acertar Alvos Ativos', rule1Highlight: '+100 PTS', rule1Result: 'Bônus de combo e nível (+0,6s por acerto)', rule2Text: 'Sistema de Combo e Ritmo', rule2Highlight: 'Multiplicador até 3,0x', rule2Result: 'Sequências maiores aceleram os saltos dos alvos', rule3Text: 'Progressão de Nível', rule3Highlight: 'Escala Contínua', rule3Result: 'Os alvos diminuem e ficam menos tempo visíveis', rule4Text: 'Erros e Tempo Esgotado', rule4HighlightPenalty: '-0,8s de penalidade', rule4HighlightZero: 'Sem penalidade (padrão)', rule4ResultPenalty: 'Subtrai 0,8s e reinicia o combo', rule4ResultZero: 'Reinicia o combo; a penalidade de tempo é opcional',
    aboutTitle: 'Sobre os Exercícios Sacádicos', aboutHeading: 'O que são movimentos sacádicos e treino do olhar?', aboutP1: 'Este exercício treina mudanças rápidas do olhar entre pontos de fixação. Em jogos competitivos, a velocidade sacádica ajuda a levar a visão até alvos em diferentes regiões da tela.', aboutP2: 'Repetir mudanças de foco entre alvos cronometrados desenvolve aquisição visual e coordenação olho-mão; não é um diagnóstico ou tratamento oftalmológico.', audienceTitle: 'Para quem é?', audienceDesc: 'Jogadores e atletas de esports que querem melhorar aquisição visual, varredura e precisão do primeiro disparo.', calibrationTitle: 'Calibração do Olhar', calibrationDesc: 'Pratique mudanças controladas do olhar entre setores da tela, mantendo fixações breves e precisas.', acquisitionTitle: 'Aquisição Rápida de Alvos', acquisitionDesc: 'Treine a velocidade entre perceber um alvo novo e executar o movimento.', accuracy: 'Precisão', avgReaction: 'Reação Média', peakLevel: 'Nível Máximo', maxCombo: 'Combo Máximo',
    scoreShareTitle: 'Exercícios Sacádicos — Minha Pontuação', scoreShareText: 'Fiz {score} (nota {grade}, nível {level}) nos Exercícios Sacádicos da SkillDrills!', scoreShareTitleShort: 'Exercícios Sacádicos', scoreShareTextShort: 'Fiz {score} nos Exercícios Sacádicos! Você consegue superar?'
  } },
  es: { saccadicGallery: {
    title: 'Ejercicios Sacádicos', subtitle: 'Saltos Oculares • Adquisición Visual', caption: 'Desplaza la mirada entre objetivos y pulsa cada uno con precisión.',
    score: 'Puntos', time: 'Tiempo', timeLeft: 'Tiempo Restante', level: 'Nivel', bestScore: 'Récord', rotateLandscape: 'Gira a horizontal para ampliar el campo de escaneo visual.', toggleMissFlash: 'Activar/desactivar flash de fallo', toggleSound: 'Activar/desactivar sonido', getReady: 'PREPÁRATE',
    rulesTitle: 'Instrucciones y Sistema de Puntuación', rule1Text: 'Acertar Objetivos Activos', rule1Highlight: '+100 PTS', rule1Result: 'Bono de combo y nivel (+0,6 s por acierto)', rule2Text: 'Sistema de Racha y Ritmo', rule2Highlight: 'Multiplicador hasta 3,0x', rule2Result: 'Las rachas aceleran los saltos de los objetivos', rule3Text: 'Progresión de Nivel', rule3Highlight: 'Escalado Continuo', rule3Result: 'Los objetivos se reducen y duran menos tiempo', rule4Text: 'Fallos y Tiempo Agotado', rule4HighlightPenalty: 'Penalización de -0,8 s', rule4HighlightZero: 'Sin penalización (por defecto)', rule4ResultPenalty: 'Resta 0,8 s y reinicia la racha', rule4ResultZero: 'Reinicia la racha; la penalización de tiempo es opcional',
    aboutTitle: 'Sobre los Ejercicios Sacádicos', aboutHeading: '¿Qué son los movimientos sacádicos y el entrenamiento de la mirada?', aboutP1: 'Este ejercicio entrena cambios rápidos de la mirada entre puntos de fijación. En los juegos competitivos, la velocidad sacádica ayuda a llevar la mirada hacia objetivos en distintas zonas de la pantalla.', aboutP2: 'Repetir cambios de foco entre objetivos cronometrados desarrolla adquisición visual y coordinación ojo-mano; no diagnostica ni trata problemas oculares.', audienceTitle: '¿Para quién está pensado?', audienceDesc: 'Jugadores y atletas de esports que quieren mejorar adquisición visual, escaneo y precisión del primer disparo.', calibrationTitle: 'Calibración de la Mirada', calibrationDesc: 'Practica desplazamientos controlados entre sectores de la pantalla con fijaciones breves y precisas.', acquisitionTitle: 'Adquisición Rápida de Objetivos', acquisitionDesc: 'Mejora el tiempo entre detectar un objetivo y ejecutar el movimiento.', accuracy: 'Precisión', avgReaction: 'Reacción Media', peakLevel: 'Nivel Máximo', maxCombo: 'Racha Máxima',
    scoreShareTitle: 'Ejercicios Sacádicos — Mi Puntuación', scoreShareText: 'He conseguido {score} (grado {grade}, nivel {level}) en Ejercicios Sacádicos de SkillDrills.', scoreShareTitleShort: 'Ejercicios Sacádicos', scoreShareTextShort: 'He conseguido {score} en Ejercicios Sacádicos. ¿Puedes superarlo?'
  } },
  ja: { saccadicGallery: {
    title: 'サッケードトレーニング', subtitle: '視線の跳躍 • 視覚ターゲット捕捉', caption: 'ターゲット間へ視線を素早く移し、正確にクリックします。', score: 'スコア', time: '時間', timeLeft: '残り時間', level: 'レベル', bestScore: 'ベストスコア', rotateLandscape: '横向きにすると、視線を動かす視野が広がります。', toggleMissFlash: 'ミス表示を切り替え', toggleSound: 'サウンドを切り替え', getReady: '準備して',
    rulesTitle: 'プレイ手順とスコア仕様', rule1Text: '表示中のターゲットを捉える', rule1Highlight: '+100 PTS', rule1Result: 'コンボ・レベルボーナス（1ヒット +0.6秒）', rule2Text: 'コンボとヒートシステム', rule2Highlight: '最大3.0倍', rule2Result: '連続成功でターゲットの切り替えが速くなる', rule3Text: 'レベル上昇', rule3Highlight: '継続スケーリング', rule3Result: 'ターゲットが小さくなり表示時間が短くなる', rule4Text: 'ミスと時間切れ', rule4HighlightPenalty: '-0.8秒ペナルティ', rule4HighlightZero: 'ペナルティなし（標準）', rule4ResultPenalty: '0.8秒減算してコンボをリセット', rule4ResultZero: 'コンボをリセット（時間ペナルティは設定で選択）',
    aboutTitle: 'サッケードトレーニングについて', aboutHeading: 'サッケードと視線移動トレーニングとは？', aboutP1: 'このトレーニングは、注視点から別のターゲットへ視線を素早く移す動きを鍛えます。競技ゲームでは、画面の異なる位置へ視線を移して標的を捉える速さが重要です。', aboutP2: '時間制限のあるターゲット間で視線を繰り返し移すことで、視覚的な捕捉と手眼協調を高めます。眼疾患の診断や治療を行うものではありません。', audienceTitle: '対象プレイヤー', audienceDesc: '視線の捕捉、視覚スキャン、初弾の正確さを高めたいゲーマーやeスポーツ選手。', calibrationTitle: '視線移動の調整', calibrationDesc: '画面の各エリアへ視線を制御して移し、短く正確に注視します。', acquisitionTitle: 'ターゲット捕捉速度', acquisitionDesc: '新しいターゲットを見つけてから手を動かすまでの時間を短くします。', accuracy: '命中精度', avgReaction: '平均反応', peakLevel: '最高レベル', maxCombo: '最大コンボ',
    scoreShareTitle: 'サッケードトレーニング — スコア', scoreShareText: 'SkillDrillsのサッケードトレーニングで{score}（評価 {grade}・レベル {level}）を記録しました！', scoreShareTitleShort: 'サッケードトレーニング', scoreShareTextShort: 'サッケードトレーニングで{score}を記録しました。挑戦しますか？'
  } },
  de: { saccadicGallery: {
    title: 'Sakkaden-Sehtraining', subtitle: 'Blicksprünge • Schnelle Zielerfassung', caption: 'Führe den Blick schnell zwischen Zielen und klicke jedes präzise an.', score: 'Punkte', time: 'Zeit', timeLeft: 'Restzeit', level: 'Level', bestScore: 'Highscore', rotateLandscape: 'Für ein breiteres Blickfeld bitte ins Querformat wechseln.', toggleMissFlash: 'Fehlblitz umschalten', toggleSound: 'Ton umschalten', getReady: 'BEREIT',
    rulesTitle: 'Anleitung und Punktesystem', rule1Text: 'Aktive Ziele treffen', rule1Highlight: '+100 PTS', rule1Result: 'Combo- und Levelbonus (+0,6 s pro Treffer)', rule2Text: 'Combo- und Heat-System', rule2Highlight: 'Bis zu 3,0x Multiplikator', rule2Result: 'Höhere Serien beschleunigen die Zielwechsel', rule3Text: 'Level-Fortschritt', rule3Highlight: 'Kontinuierliche Skalierung', rule3Result: 'Ziele werden kleiner und bleiben kürzer sichtbar', rule4Text: 'Fehlklicks und Zeitablauf', rule4HighlightPenalty: '-0,8 s Abzug', rule4HighlightZero: 'Keine Abzüge (Standard)', rule4ResultPenalty: 'Zieht 0,8 s ab und setzt Combo zurück', rule4ResultZero: 'Setzt Combo zurück; Zeitabzug ist optional',
    aboutTitle: 'Über das Sakkaden-Sehtraining', aboutHeading: 'Was sind Sakkaden und Blicksprung-Training?', aboutP1: 'Dieser Drill trainiert schnelle Blickwechsel zwischen Fixationspunkten. In kompetitiven Spielen beeinflusst die Sakkadengeschwindigkeit, wie schnell der Blick Ziele in verschiedenen Bildschirmbereichen erreicht.', aboutP2: 'Wiederholte Blickwechsel zwischen zeitlich begrenzten Zielen fördern visuelle Zielerfassung und Hand-Auge-Koordination; der Drill ersetzt keine augenärztliche Untersuchung.', audienceTitle: 'Für wen ist der Drill?', audienceDesc: 'Für Gamer und Esportler, die Blickerfassung, visuelles Scannen und Präzision beim ersten Schuss verbessern wollen.', calibrationTitle: 'Blicksprünge kalibrieren', calibrationDesc: 'Übe kontrollierte Blickwechsel zwischen Bildschirmsektoren mit kurzen, präzisen Fixationen.', acquisitionTitle: 'Schnelle Zielerfassung', acquisitionDesc: 'Verkürze die Zeit zwischen dem Erkennen eines neuen Ziels und der Bewegung.', accuracy: 'Genauigkeit', avgReaction: 'Durchschn. Reaktion', peakLevel: 'Höchstes Level', maxCombo: 'Max. Combo',
    scoreShareTitle: 'Sakkaden-Sehtraining — mein Ergebnis', scoreShareText: 'Ich habe {score} (Note {grade}, Level {level}) im Sakkaden-Sehtraining von SkillDrills erzielt!', scoreShareTitleShort: 'Sakkaden-Sehtraining', scoreShareTextShort: 'Ich habe {score} im Sakkaden-Sehtraining erzielt. Schaffst du mehr?'
  } },
  ko: { saccadicGallery: {
    title: '단속성 안구운동 훈련', subtitle: '시선 도약 • 빠른 시각 포착', caption: '타깃 사이로 시선을 빠르게 옮기고 각각 정확하게 클릭하세요.', score: '점수', time: '시간', timeLeft: '남은 시간', level: '레벨', bestScore: '최고 점수', rotateLandscape: '가로 모드로 전환하면 더 넓은 시야에서 훈련할 수 있습니다.', toggleMissFlash: '미스 플래시 전환', toggleSound: '사운드 전환', getReady: '준비하세요',
    rulesTitle: '훈련 규칙 및 점수 체계', rule1Text: '활성 타깃 적중', rule1Highlight: '+100 PTS', rule1Result: '콤보·레벨 보너스 (적중마다 +0.6초)', rule2Text: '콤보 및 히트 시스템', rule2Highlight: '최대 3.0배 배수', rule2Result: '연속 적중할수록 타깃 전환 속도 증가', rule3Text: '레벨 진행', rule3Highlight: '연속 난이도 상승', rule3Result: '타깃이 작아지고 노출 시간이 짧아짐', rule4Text: '미스 및 시간 초과', rule4HighlightPenalty: '-0.8초 차감', rule4HighlightZero: '차감 없음 (기본값)', rule4ResultPenalty: '0.8초를 차감하고 콤보 초기화', rule4ResultZero: '콤보 초기화 (시간 차감은 설정에서 선택)',
    aboutTitle: '단속성 안구운동 훈련 안내', aboutHeading: '단속성 안구운동과 시선 도약 훈련이란?', aboutP1: '이 훈련은 한 고정점에서 다른 타깃으로 시선을 빠르게 옮기는 움직임을 연습합니다. 경쟁 게임에서는 화면의 서로 다른 영역에 있는 표적을 얼마나 빨리 포착하는지가 중요합니다.', aboutP2: '시간 제한 타깃 사이에서 시선을 반복적으로 이동하면 시각 포착과 눈-손 협응을 기를 수 있습니다. 안과 질환을 진단하거나 치료하는 도구는 아닙니다.', audienceTitle: '추천 대상', audienceDesc: '시선 포착, 시각 스캔, 첫 발 정확도를 높이고 싶은 게이머와 e스포츠 선수.', calibrationTitle: '시선 도약 보정', calibrationDesc: '화면 구역 사이로 시선을 통제해 옮기며 짧고 정확하게 고정하는 연습을 하세요.', acquisitionTitle: '빠른 타깃 포착', acquisitionDesc: '새 타깃을 인지한 뒤 손을 움직이기까지의 시간을 줄입니다.', accuracy: '정확도', avgReaction: '평균 반응', peakLevel: '최고 레벨', maxCombo: '최대 콤보',
    scoreShareTitle: '단속성 안구운동 훈련 — 내 점수', scoreShareText: 'SkillDrills 단속성 안구운동 훈련에서 {score}점(등급 {grade}, 레벨 {level})을 기록했습니다!', scoreShareTitleShort: '단속성 안구운동 훈련', scoreShareTextShort: '단속성 안구운동 훈련에서 {score}점을 기록했습니다. 도전해 보세요!'
  } },
  fr: { saccadicGallery: {
    title: 'Exercices Saccadiques', subtitle: 'Sauts du Regard • Acquisition Visuelle', caption: 'Déplacez rapidement le regard entre les cibles et cliquez avec précision.', score: 'Score', time: 'Temps', timeLeft: 'Temps restant', level: 'Niveau', bestScore: 'Meilleur score', rotateLandscape: 'Passez en mode paysage pour élargir le champ de balayage visuel.', toggleMissFlash: 'Activer/désactiver le flash d’erreur', toggleSound: 'Activer/désactiver le son', getReady: 'PRÉPAREZ-VOUS',
    rulesTitle: 'Consignes et système de score', rule1Text: 'Toucher les cibles actives', rule1Highlight: '+100 PTS', rule1Result: 'Bonus de combo et de niveau (+0,6 s par cible)', rule2Text: 'Système de combo et de rythme', rule2Highlight: 'Multiplicateur jusqu’à 3,0x', rule2Result: 'Les séries accélèrent les changements de cible', rule3Text: 'Progression du niveau', rule3Highlight: 'Échelle continue', rule3Result: 'Les cibles rétrécissent et restent visibles moins longtemps', rule4Text: 'Erreurs et délai dépassé', rule4HighlightPenalty: '-0,8 s de pénalité', rule4HighlightZero: 'Aucune pénalité (par défaut)', rule4ResultPenalty: 'Retire 0,8 s et réinitialise le combo', rule4ResultZero: 'Réinitialise le combo ; la pénalité de temps est optionnelle',
    aboutTitle: 'À propos des exercices saccadiques', aboutHeading: 'Que sont les mouvements saccadiques et leur entraînement ?', aboutP1: 'Cet exercice entraîne les déplacements rapides du regard entre des points de fixation. Dans les jeux compétitifs, la vitesse saccadique aide à atteindre une cible située dans une autre zone de l’écran.', aboutP2: 'Répéter ces changements de regard entre des cibles chronométrées développe l’acquisition visuelle et la coordination œil-main ; ce jeu ne remplace pas un examen ophtalmologique.', audienceTitle: 'À qui s’adresse cet exercice ?', audienceDesc: 'Aux joueurs et sportifs esport qui veulent améliorer l’acquisition visuelle, le balayage et la précision du premier tir.', calibrationTitle: 'Calibrer le regard', calibrationDesc: 'Entraînez des déplacements contrôlés entre les secteurs de l’écran avec des fixations brèves et précises.', acquisitionTitle: 'Acquisition rapide des cibles', acquisitionDesc: 'Réduisez le délai entre la détection d’une nouvelle cible et le mouvement.', accuracy: 'Précision', avgReaction: 'Réaction moyenne', peakLevel: 'Niveau maximal', maxCombo: 'Combo maximal',
    scoreShareTitle: 'Exercices saccadiques — mon score', scoreShareText: 'J’ai obtenu {score} (note {grade}, niveau {level}) dans les Exercices saccadiques de SkillDrills !', scoreShareTitleShort: 'Exercices saccadiques', scoreShareTextShort: 'J’ai obtenu {score} dans les Exercices saccadiques. Pouvez-vous faire mieux ?'
  } }
};
