// app/sitemap.js
// Dynamic XML sitemap. Served at /sitemap.xml via the rewrite in next.config.js.
//
// Design rules this file follows:
//
//  1. One source of truth. Drill URLs come from DRILLS (lib/drillsRegistry.js),
//     the same list the hubs, the search page and scripts/notify-indexnow.js use,
//     so a renamed or deleted drill can never leave a 404 in the sitemap.
//  2. Only canonical, indexable, 200-status URLs. No trailing slashes (they 308
//     via next.config.js), no redirected legacy paths, and nothing marked
//     noindex — /search is deliberately absent because its metadata sets
//     index:false, and a noindex URL in a sitemap is a contradictory signal that
//     wastes crawl budget.
//  3. Honest lastModified. Dates are per-section and hand-maintained. They must
//     reflect when that section's content actually changed. Never derive them
//     from Date.now(): a sitemap where every page claims to have changed today
//     gets its freshness signal discounted entirely.
//  4. Differentiated priority. Google ignores this field, but Bing and Yandex
//     still read it, and a sitemap where 90 of 93 URLs share the same 0.85 tells
//     them nothing. The values below rank pages by the traffic they actually
//     earn or realistically can earn, measured in Search Console.

import { DRILLS } from '../lib/drillsRegistry';
import { LOCALES, DEFAULT_LOCALE, LOCALIZED_ROUTES, hasLocalizedRoute, localeUrl, getAlternateLanguages } from '../lib/i18n/locales';

const BASE_URL = 'https://skilldrills.online';

// Bump the entry for a section when that section's copy or drills genuinely change.
const UPDATED = {
  // The locale trees were rebuilt and re-shipped together on 2026-09-22.
  localized: '2026-09-22',
  home: '2026-10-07',
  directory: '2026-08-21',
  // Every hub was rewritten in the 2026-08-21 crawlability pass (SSR restored,
  // H1s and titles rewritten). The six hubs retargeted on 2026-08-25 carry that
  // date via UPDATED_OVERRIDES below; this stays the date for the ones that did
  // not change, so /drills/visual does not inherit a bump it never earned.
  hub: '2026-08-21',
  // Drill bodies became visible to crawlers in the same pass (the accordion fix).
  drill: '2026-08-21',
  // visual-tracking additionally got per-drill long-form guides.
  'visual-tracking': '2026-08-21',
  legal: '2026-08-22',
  privacy: '2026-10-01',
};

// Per-URL overrides, for when a subset of a section changes rather than all of
// it. Bumping the whole `drill` section for 12 retargeted pages would tell
// crawlers that all 81 changed; they would recrawl 69 unchanged pages, find
// nothing new, and learn to discount this field. Rule 3 above is only worth
// anything if it is applied at the granularity the change actually happened at.
//
// 2026-08-25: title + H1 sub-line + internal anchor text retargeted onto
// measured Bing search demand.
const UPDATED_OVERRIDES = {
  '/drills/physical/reflex-training/drop-catch': '2026-09-20',
  '/drills/physical/reflex-training/quick-dodge': '2026-09-20',
  '/drills/physical/reflex-training/reaction-chain': '2026-09-20',
  '/drills/physical/balance-training/stability-challenge': '2026-09-20',
  '/drills/physical/coordination/complex-pattern': '2026-09-20',
  '/drills/physical/coordination/cross-body-movement': '2026-09-20',
  '/drills/physical/coordination/dynamic-grid-evasion': '2026-09-20',
  '/drills/physical/fitness/agility-ladder': '2026-09-20',
  '/drills/physical/fitness/jump-sequence': '2026-09-20',
  '/drills/physical/fitness/speed-drill': '2026-09-20',
  '/drills/visual/depth-perception/distance-judgment': '2026-09-20',
  '/drills/visual/reaction-speed/light-reaction': '2026-09-20',
  '/drills/visual/reaction-speed/go/no-go': '2026-09-20',
  '/drills/visual/visual-recognition/visual-search': '2026-09-20',
  '/drills/visual-tracking/constant-slow-pursuit': '2026-09-20',
  '/drills/visual-tracking/directional-chaos-pursuit': '2026-09-20',
  '/drills/visual-tracking/dynamic-evasion-pursuit': '2026-09-20',
  '/drills/visual-tracking/ghosting-suppress-pursuit': '2026-09-20',
  '/drills/visual-tracking/infinity-pursuit': '2026-09-20',
  '/drills/visual-tracking/momentum-teleport-pursuit': '2026-09-20',
    '/drills/visual-tracking/peripheral-ping-pursuit': '2026-09-20',
    '/drills/visual-tracking/predictive-pursuit': '2026-09-20',
    '/drills/visual-tracking/sine-wave-pursuit': '2026-09-20',
  '/drills/visual-tracking/spatial-shift-pursuit': '2026-09-20',
  '/drills/visual-tracking/split-screen-tracking': '2026-09-20',
  '/drills/visual-tracking/staircase-step': '2026-09-20',
  '/drills/visual-tracking/strobe-prediction-pursuit': '2026-09-20',
  '/drills/visual-tracking/triangular-pursuit': '2026-09-20',
  '/drills/visual-tracking/zig-zag-path-pursuit': '2026-09-20',
  '/drills/visual/tracking-accuracy/moving-target': '2026-09-20',
  '/drills/motor/movement-speed/rapid-tapping': '2026-08-25',
  '/drills/motor/movement-speed/keyboard-recognition': '2026-08-25',
  '/drills/motor/hand-eye-coordination/precision-flick-shot': '2026-08-25',
  '/drills/cognitive/focus/distraction-fighter': '2026-08-25',
  '/drills/cognitive/focus/concentration-grid': '2026-08-25',
  '/drills/cognitive/processing-speed/rsvp-reader': '2026-08-25',
  '/drills/cognitive/processing-speed/symbol-matching': '2026-08-25',
  '/drills/memory/short-term-memory/color-sequence': '2026-08-25',
  '/drills/memory/short-term-memory/word-recall': '2026-08-25',
  '/drills/memory/spatial-memory/grid-memorization': '2026-08-25',
  '/drills/physical/reflex-training/peripheral-threat-sweeper': '2026-09-20',
  '/drills/visual/tracking-accuracy/pursuit-tracker': '2026-09-20',
  '/drills/visual/tracking-accuracy/multiple-targets': '2026-09-20',
  '/drills/visual/visual-recognition/entropic-grid': '2026-09-20',
  '/drills/visual/visual-recognition/rhythm-anomaly': '2026-09-20',
  '/drills/visual': '2026-09-20',
  // Hub titles retargeted the same day. /drills and /drills/visual-tracking
  // /drills/visual-tracking were deliberately left alone, so they are absent.
  '/drills/cognitive': '2026-08-25',
  '/drills/memory': '2026-08-25',
  '/drills/fps': '2026-08-25',
  '/drills/motor': '2026-08-25',
  '/drills/physical': '2026-09-20',
  '/drills/reaction-speed': '2026-08-25',
};

// 2026-10-07 audit pass. Keys that start with a locale prefix date only that
// locale's page; bare routes date every version of the route.
const AUDIT_2026_10_07 = [
  '/',
  '/drills/fps',
  '/drills/cognitive',
  '/drills/visual',
  '/drills/visual-tracking',
  '/drills/visual/tracking-accuracy/pursuit-tracker',
  '/drills/visual/visual-recognition/entropic-grid',
  '/drills/visual/visual-recognition/rhythm-anomaly',
  '/drills/visual/visual-recognition/visual-search',
  '/drills/cognitive/processing-speed/symbol-matching',
  '/drills/motor/movement-speed/keyboard-recognition',
  ...['de', 'es', 'fr', 'pt', 'ja', 'ko'].map((l) => `/${l}/drills/memory/working-memory/n-back`),
  ...['es', 'fr', 'pt'].flatMap((l) => [`/${l}/drills/visual-tracking/triangular-pursuit`, `/${l}/drills/visual-tracking/zig-zag-path-pursuit`]),
  '/fr/drills/motor/hand-eye-coordination/aim-trainer',
  ...[
    '/drills/reaction-speed/barrier-sequence-pursuit',
    '/drills/reaction-speed/fps-tracking-trainer',
    '/drills/reaction-speed/market-doors-pursuit',
    '/drills/reaction-speed/reaction-game',
    '/drills/reaction-speed/reflex-training-drill',
    '/drills/reaction-speed/visual-tracking-speed-test',
    '/drills/visual-tracking/constant-slow-pursuit',
  ].flatMap((route) => ['ko', 'ja', 'de', 'pt', 'es', 'fr'].map((l) => `/${l}${route}`)),
  '/de/drills/visual-tracking/directional-chaos-pursuit',
  '/de/drills/visual-tracking/dynamic-evasion-pursuit',
  '/de/drills/fps/target-acquisition',
  '/de/drills/physical/fitness/speed-drill',
  '/de/drills/physical/fitness/jump-sequence',
  '/de/drills/physical/coordination/dynamic-grid-evasion',
  '/de/drills/visual/depth-perception/distance-judgment',
  '/es/drills/physical/fitness/jump-sequence',
  '/es/drills/reaction-speed/reaction-time-test',
  '/es/drills/visual/depth-perception/distance-judgment',
  '/es/drills/visual/reaction-speed/light-reaction',
  '/fr/drills/physical/fitness/jump-sequence',
  '/fr/drills/visual-tracking',
  '/fr/drills/cognitive/processing-speed/reaction-time',
  '/pt/drills/cognitive/processing-speed/reaction-time',
  '/pt/drills/visual/depth-perception/distance-judgment',
  '/pt/drills/visual/reaction-speed/light-reaction',
  ...['de', 'es', 'fr', 'ja', 'ko'].map((l) => `/${l}/drills`),
];
for (const path of AUDIT_2026_10_07) UPDATED_OVERRIDES[path] = '2026-10-07';

const CHANGED_2026_10_08 = [
  '/about',
  '/de/drills',
  '/de/drills/cognitive/attention/concentration-stamina',
  '/de/drills/cognitive/attention/divided-attention',
  '/de/drills/cognitive/attention/multi-tasking',
  '/de/drills/cognitive/focus/concentration-grid',
  '/de/drills/cognitive/focus/distraction-fighter',
  '/de/drills/cognitive/processing-speed/reaction-time',
  '/de/drills/cognitive/processing-speed/rsvp-reader',
  '/de/drills/cognitive/processing-speed/symbol-matching',
  '/de/drills/fps/180-degree-awareness',
  '/de/drills/fps/angle-hold-trainer',
  '/de/drills/fps/anti-strafe-jitter-duel',
  '/de/drills/fps/anti-zigzag-movement-trainer',
  '/de/drills/fps/flick-shot-training',
  '/de/drills/fps/flow-state',
  '/de/drills/fps/instant-response',
  '/de/drills/fps/micro-correction-precision',
  '/de/drills/fps/pro-smooth-pursuit',
  '/de/drills/fps/recoil-control',
  '/de/drills/fps/strafe-tracking',
  '/de/drills/fps/target-acquisition',
  '/de/drills/fps/target-prioritization',
  '/de/drills/fps/target-switching-swarm',
  '/de/drills/fps/vertical-air-track',
  '/de/drills/memory/short-term-memory/color-sequence',
  '/de/drills/memory/short-term-memory/digit-span',
  '/de/drills/memory/short-term-memory/word-recall',
  '/de/drills/memory/spatial-memory/grid-memorization',
  '/de/drills/memory/spatial-memory/object-location',
  '/de/drills/memory/spatial-memory/path-tracing',
  '/de/drills/memory/working-memory/n-back',
  '/de/drills/motor',
  '/de/drills/motor/hand-eye-coordination/aim-trainer',
  '/de/drills/motor/hand-eye-coordination/drag-and-drop',
  '/de/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/de/drills/motor/movement-speed/finger-sequencing',
  '/de/drills/motor/movement-speed/keyboard-recognition',
  '/de/drills/motor/movement-speed/rapid-tapping',
  '/de/drills/motor/precision-control/steady-hand',
  '/de/drills/motor/precision-control/tracing',
  '/de/drills/physical',
  '/de/drills/physical/balance-training/stability-challenge',
  '/de/drills/physical/coordination/complex-pattern',
  '/de/drills/physical/coordination/cross-body-movement',
  '/de/drills/physical/coordination/dynamic-grid-evasion',
  '/de/drills/physical/fitness/agility-ladder',
  '/de/drills/physical/fitness/jump-sequence',
  '/de/drills/physical/fitness/speed-drill',
  '/de/drills/physical/reflex-training/drop-catch',
  '/de/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/de/drills/physical/reflex-training/quick-dodge',
  '/de/drills/physical/reflex-training/reaction-chain',
  '/de/drills/reaction-speed/reaction-time-test',
  '/de/drills/reaction-speed/saccadic-gallery',
  '/de/drills/visual',
  '/de/drills/visual-tracking/directional-chaos-pursuit',
  '/de/drills/visual-tracking/dynamic-evasion-pursuit',
  '/de/drills/visual-tracking/ghosting-suppress-pursuit',
  '/de/drills/visual-tracking/infinity-pursuit',
  '/de/drills/visual-tracking/momentum-teleport-pursuit',
  '/de/drills/visual-tracking/peripheral-ping-pursuit',
  '/de/drills/visual-tracking/predictive-pursuit',
  '/de/drills/visual-tracking/sine-wave-pursuit',
  '/de/drills/visual-tracking/spatial-shift-pursuit',
  '/de/drills/visual-tracking/split-screen-tracking',
  '/de/drills/visual-tracking/staircase-step',
  '/de/drills/visual-tracking/strobe-prediction-pursuit',
  '/de/drills/visual-tracking/triangular-pursuit',
  '/de/drills/visual-tracking/zig-zag-path-pursuit',
  '/de/drills/visual/depth-perception/distance-judgment',
  '/de/drills/visual/reaction-speed/light-reaction',
  '/de/drills/visual/tracking-accuracy/moving-target',
  '/de/drills/visual/tracking-accuracy/multiple-targets',
  '/de/drills/visual/tracking-accuracy/pursuit-tracker',
  '/de/drills/visual/visual-recognition/entropic-grid',
  '/de/drills/visual/visual-recognition/rhythm-anomaly',
  '/de/drills/visual/visual-recognition/visual-search',
  '/drills/cognitive/attention/concentration-stamina',
  '/drills/cognitive/attention/divided-attention',
  '/drills/cognitive/attention/multi-tasking',
  '/drills/cognitive/focus/concentration-grid',
  '/drills/cognitive/focus/distraction-fighter',
  '/drills/cognitive/processing-speed/reaction-time',
  '/drills/cognitive/processing-speed/rsvp-reader',
  '/drills/cognitive/processing-speed/symbol-matching',
  '/drills/fps/180-degree-awareness',
  '/drills/fps/angle-hold-trainer',
  '/drills/fps/anti-strafe-jitter-duel',
  '/drills/fps/anti-zigzag-movement-trainer',
  '/drills/fps/flick-shot-training',
  '/drills/fps/flow-state',
  '/drills/fps/instant-response',
  '/drills/fps/micro-correction-precision',
  '/drills/fps/pro-smooth-pursuit',
  '/drills/fps/recoil-control',
  '/drills/fps/strafe-tracking',
  '/drills/fps/target-acquisition',
  '/drills/fps/target-prioritization',
  '/drills/fps/target-switching-swarm',
  '/drills/fps/vertical-air-track',
  '/drills/memory/short-term-memory/color-sequence',
  '/drills/memory/short-term-memory/digit-span',
  '/drills/memory/short-term-memory/word-recall',
  '/drills/memory/spatial-memory/grid-memorization',
  '/drills/memory/spatial-memory/object-location',
  '/drills/memory/spatial-memory/path-tracing',
  '/drills/memory/working-memory/n-back',
  '/drills/motor',
  '/drills/motor/hand-eye-coordination/aim-trainer',
  '/drills/motor/hand-eye-coordination/drag-and-drop',
  '/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/drills/motor/movement-speed/finger-sequencing',
  '/drills/motor/movement-speed/keyboard-recognition',
  '/drills/motor/movement-speed/rapid-tapping',
  '/drills/motor/precision-control/steady-hand',
  '/drills/motor/precision-control/tracing',
  '/drills/physical',
  '/drills/physical/balance-training/stability-challenge',
  '/drills/physical/coordination/complex-pattern',
  '/drills/physical/coordination/cross-body-movement',
  '/drills/physical/coordination/dynamic-grid-evasion',
  '/drills/physical/fitness/agility-ladder',
  '/drills/physical/fitness/jump-sequence',
  '/drills/physical/fitness/speed-drill',
  '/drills/physical/reflex-training/drop-catch',
  '/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/drills/physical/reflex-training/quick-dodge',
  '/drills/physical/reflex-training/reaction-chain',
  '/drills/visual',
  '/drills/visual-tracking/split-screen-tracking',
  '/drills/visual-tracking/staircase-step',
  '/drills/visual/depth-perception/distance-judgment',
  '/drills/visual/reaction-speed/go/no-go',
  '/drills/visual/reaction-speed/light-reaction',
  '/drills/visual/tracking-accuracy/moving-target',
  '/drills/visual/tracking-accuracy/multiple-targets',
  '/drills/visual/tracking-accuracy/pursuit-tracker',
  '/drills/visual/visual-recognition/entropic-grid',
  '/drills/visual/visual-recognition/rhythm-anomaly',
  '/drills/visual/visual-recognition/visual-search',
  '/es/drills',
  '/es/drills/cognitive',
  '/es/drills/cognitive/attention/concentration-stamina',
  '/es/drills/cognitive/attention/divided-attention',
  '/es/drills/cognitive/attention/multi-tasking',
  '/es/drills/cognitive/focus/concentration-grid',
  '/es/drills/cognitive/focus/distraction-fighter',
  '/es/drills/cognitive/processing-speed/reaction-time',
  '/es/drills/cognitive/processing-speed/rsvp-reader',
  '/es/drills/cognitive/processing-speed/symbol-matching',
  '/es/drills/fps',
  '/es/drills/fps/180-degree-awareness',
  '/es/drills/fps/angle-hold-trainer',
  '/es/drills/fps/anti-strafe-jitter-duel',
  '/es/drills/fps/anti-zigzag-movement-trainer',
  '/es/drills/fps/flick-shot-training',
  '/es/drills/fps/flow-state',
  '/es/drills/fps/instant-response',
  '/es/drills/fps/micro-correction-precision',
  '/es/drills/fps/pro-smooth-pursuit',
  '/es/drills/fps/recoil-control',
  '/es/drills/fps/strafe-tracking',
  '/es/drills/fps/target-acquisition',
  '/es/drills/fps/target-prioritization',
  '/es/drills/fps/target-switching-swarm',
  '/es/drills/fps/vertical-air-track',
  '/es/drills/memory/short-term-memory/color-sequence',
  '/es/drills/memory/short-term-memory/digit-span',
  '/es/drills/memory/short-term-memory/word-recall',
  '/es/drills/memory/spatial-memory/grid-memorization',
  '/es/drills/memory/spatial-memory/object-location',
  '/es/drills/memory/spatial-memory/path-tracing',
  '/es/drills/memory/working-memory/n-back',
  '/es/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/es/drills/motor/movement-speed/finger-sequencing',
  '/es/drills/motor/movement-speed/keyboard-recognition',
  '/es/drills/motor/movement-speed/rapid-tapping',
  '/es/drills/motor/precision-control/steady-hand',
  '/es/drills/motor/precision-control/tracing',
  '/es/drills/physical/balance-training/stability-challenge',
  '/es/drills/physical/coordination/complex-pattern',
  '/es/drills/physical/coordination/cross-body-movement',
  '/es/drills/physical/coordination/dynamic-grid-evasion',
  '/es/drills/physical/fitness/agility-ladder',
  '/es/drills/physical/fitness/jump-sequence',
  '/es/drills/physical/fitness/speed-drill',
  '/es/drills/physical/reflex-training/drop-catch',
  '/es/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/es/drills/physical/reflex-training/quick-dodge',
  '/es/drills/physical/reflex-training/reaction-chain',
  '/es/drills/reaction-speed/reaction-time-test',
  '/es/drills/reaction-speed/saccadic-gallery',
  '/es/drills/visual',
  '/es/drills/visual-tracking/directional-chaos-pursuit',
  '/es/drills/visual-tracking/dynamic-evasion-pursuit',
  '/es/drills/visual-tracking/ghosting-suppress-pursuit',
  '/es/drills/visual-tracking/momentum-teleport-pursuit',
  '/es/drills/visual-tracking/peripheral-ping-pursuit',
  '/es/drills/visual-tracking/predictive-pursuit',
  '/es/drills/visual-tracking/sine-wave-pursuit',
  '/es/drills/visual-tracking/spatial-shift-pursuit',
  '/es/drills/visual-tracking/split-screen-tracking',
  '/es/drills/visual-tracking/staircase-step',
  '/es/drills/visual-tracking/strobe-prediction-pursuit',
  '/es/drills/visual-tracking/triangular-pursuit',
  '/es/drills/visual-tracking/zig-zag-path-pursuit',
  '/es/drills/visual/depth-perception/distance-judgment',
  '/es/drills/visual/reaction-speed/light-reaction',
  '/es/drills/visual/tracking-accuracy/moving-target',
  '/es/drills/visual/tracking-accuracy/multiple-targets',
  '/es/drills/visual/tracking-accuracy/pursuit-tracker',
  '/es/drills/visual/visual-recognition/entropic-grid',
  '/es/drills/visual/visual-recognition/rhythm-anomaly',
  '/fr/drills',
  '/fr/drills/cognitive/attention/concentration-stamina',
  '/fr/drills/cognitive/attention/divided-attention',
  '/fr/drills/cognitive/attention/multi-tasking',
  '/fr/drills/cognitive/focus/concentration-grid',
  '/fr/drills/cognitive/focus/distraction-fighter',
  '/fr/drills/cognitive/processing-speed/reaction-time',
  '/fr/drills/cognitive/processing-speed/rsvp-reader',
  '/fr/drills/cognitive/processing-speed/symbol-matching',
  '/fr/drills/fps',
  '/fr/drills/fps/180-degree-awareness',
  '/fr/drills/fps/angle-hold-trainer',
  '/fr/drills/fps/anti-strafe-jitter-duel',
  '/fr/drills/fps/anti-zigzag-movement-trainer',
  '/fr/drills/fps/flick-shot-training',
  '/fr/drills/fps/flow-state',
  '/fr/drills/fps/instant-response',
  '/fr/drills/fps/micro-correction-precision',
  '/fr/drills/fps/pro-smooth-pursuit',
  '/fr/drills/fps/recoil-control',
  '/fr/drills/fps/strafe-tracking',
  '/fr/drills/fps/target-acquisition',
  '/fr/drills/fps/target-prioritization',
  '/fr/drills/fps/target-switching-swarm',
  '/fr/drills/fps/vertical-air-track',
  '/fr/drills/memory/short-term-memory/color-sequence',
  '/fr/drills/memory/short-term-memory/digit-span',
  '/fr/drills/memory/short-term-memory/word-recall',
  '/fr/drills/memory/spatial-memory/grid-memorization',
  '/fr/drills/memory/spatial-memory/object-location',
  '/fr/drills/memory/spatial-memory/path-tracing',
  '/fr/drills/memory/working-memory/n-back',
  '/fr/drills/motor',
  '/fr/drills/motor/hand-eye-coordination/aim-trainer',
  '/fr/drills/motor/movement-speed/finger-sequencing',
  '/fr/drills/motor/movement-speed/keyboard-recognition',
  '/fr/drills/motor/movement-speed/rapid-tapping',
  '/fr/drills/motor/precision-control/steady-hand',
  '/fr/drills/motor/precision-control/tracing',
  '/fr/drills/physical',
  '/fr/drills/physical/balance-training/stability-challenge',
  '/fr/drills/physical/coordination/complex-pattern',
  '/fr/drills/physical/coordination/cross-body-movement',
  '/fr/drills/physical/coordination/dynamic-grid-evasion',
  '/fr/drills/physical/fitness/agility-ladder',
  '/fr/drills/physical/fitness/jump-sequence',
  '/fr/drills/physical/fitness/speed-drill',
  '/fr/drills/physical/reflex-training/drop-catch',
  '/fr/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/fr/drills/physical/reflex-training/quick-dodge',
  '/fr/drills/physical/reflex-training/reaction-chain',
  '/fr/drills/reaction-speed/reaction-time-test',
  '/fr/drills/reaction-speed/saccadic-gallery',
  '/fr/drills/visual',
  '/fr/drills/visual-tracking/directional-chaos-pursuit',
  '/fr/drills/visual-tracking/dynamic-evasion-pursuit',
  '/fr/drills/visual-tracking/ghosting-suppress-pursuit',
  '/fr/drills/visual-tracking/infinity-pursuit',
  '/fr/drills/visual-tracking/momentum-teleport-pursuit',
  '/fr/drills/visual-tracking/peripheral-ping-pursuit',
  '/fr/drills/visual-tracking/predictive-pursuit',
  '/fr/drills/visual-tracking/sine-wave-pursuit',
  '/fr/drills/visual-tracking/spatial-shift-pursuit',
  '/fr/drills/visual-tracking/split-screen-tracking',
  '/fr/drills/visual-tracking/staircase-step',
  '/fr/drills/visual-tracking/strobe-prediction-pursuit',
  '/fr/drills/visual-tracking/triangular-pursuit',
  '/fr/drills/visual-tracking/zig-zag-path-pursuit',
  '/fr/drills/visual/depth-perception/distance-judgment',
  '/fr/drills/visual/reaction-speed/light-reaction',
  '/fr/drills/visual/tracking-accuracy/moving-target',
  '/fr/drills/visual/tracking-accuracy/multiple-targets',
  '/fr/drills/visual/tracking-accuracy/pursuit-tracker',
  '/fr/drills/visual/visual-recognition/entropic-grid',
  '/ja',
  '/ja/drills',
  '/ja/drills/cognitive',
  '/ja/drills/cognitive/attention/concentration-stamina',
  '/ja/drills/cognitive/attention/divided-attention',
  '/ja/drills/cognitive/attention/multi-tasking',
  '/ja/drills/cognitive/focus/concentration-grid',
  '/ja/drills/cognitive/focus/distraction-fighter',
  '/ja/drills/cognitive/processing-speed/reaction-time',
  '/ja/drills/cognitive/processing-speed/rsvp-reader',
  '/ja/drills/cognitive/processing-speed/symbol-matching',
  '/ja/drills/fps',
  '/ja/drills/fps/180-degree-awareness',
  '/ja/drills/fps/angle-hold-trainer',
  '/ja/drills/fps/anti-strafe-jitter-duel',
  '/ja/drills/fps/anti-zigzag-movement-trainer',
  '/ja/drills/fps/flick-shot-training',
  '/ja/drills/fps/flow-state',
  '/ja/drills/fps/instant-response',
  '/ja/drills/fps/micro-correction-precision',
  '/ja/drills/fps/pro-smooth-pursuit',
  '/ja/drills/fps/recoil-control',
  '/ja/drills/fps/strafe-tracking',
  '/ja/drills/fps/target-acquisition',
  '/ja/drills/fps/target-prioritization',
  '/ja/drills/fps/target-switching-swarm',
  '/ja/drills/fps/vertical-air-track',
  '/ja/drills/memory/short-term-memory/color-sequence',
  '/ja/drills/memory/short-term-memory/digit-span',
  '/ja/drills/memory/short-term-memory/word-recall',
  '/ja/drills/memory/spatial-memory/grid-memorization',
  '/ja/drills/memory/spatial-memory/object-location',
  '/ja/drills/memory/spatial-memory/path-tracing',
  '/ja/drills/memory/working-memory/n-back',
  '/ja/drills/motor',
  '/ja/drills/motor/hand-eye-coordination/aim-trainer',
  '/ja/drills/motor/hand-eye-coordination/drag-and-drop',
  '/ja/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/ja/drills/motor/movement-speed/finger-sequencing',
  '/ja/drills/motor/movement-speed/keyboard-recognition',
  '/ja/drills/motor/movement-speed/rapid-tapping',
  '/ja/drills/motor/precision-control/steady-hand',
  '/ja/drills/motor/precision-control/tracing',
  '/ja/drills/physical',
  '/ja/drills/physical/balance-training/stability-challenge',
  '/ja/drills/physical/coordination/complex-pattern',
  '/ja/drills/physical/coordination/cross-body-movement',
  '/ja/drills/physical/coordination/dynamic-grid-evasion',
  '/ja/drills/physical/fitness/agility-ladder',
  '/ja/drills/physical/fitness/jump-sequence',
  '/ja/drills/physical/fitness/speed-drill',
  '/ja/drills/physical/reflex-training/drop-catch',
  '/ja/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/ja/drills/physical/reflex-training/quick-dodge',
  '/ja/drills/physical/reflex-training/reaction-chain',
  '/ja/drills/reaction-speed/reaction-time-test',
  '/ja/drills/reaction-speed/saccadic-gallery',
  '/ja/drills/visual-tracking',
  '/ja/drills/visual-tracking/directional-chaos-pursuit',
  '/ja/drills/visual-tracking/dynamic-evasion-pursuit',
  '/ja/drills/visual-tracking/ghosting-suppress-pursuit',
  '/ja/drills/visual-tracking/infinity-pursuit',
  '/ja/drills/visual-tracking/momentum-teleport-pursuit',
  '/ja/drills/visual-tracking/peripheral-ping-pursuit',
  '/ja/drills/visual-tracking/predictive-pursuit',
  '/ja/drills/visual-tracking/sine-wave-pursuit',
  '/ja/drills/visual-tracking/spatial-shift-pursuit',
  '/ja/drills/visual-tracking/split-screen-tracking',
  '/ja/drills/visual-tracking/staircase-step',
  '/ja/drills/visual-tracking/strobe-prediction-pursuit',
  '/ja/drills/visual-tracking/triangular-pursuit',
  '/ja/drills/visual-tracking/zig-zag-path-pursuit',
  '/ja/drills/visual/depth-perception/distance-judgment',
  '/ja/drills/visual/reaction-speed/go/no-go',
  '/ja/drills/visual/reaction-speed/light-reaction',
  '/ja/drills/visual/tracking-accuracy/moving-target',
  '/ja/drills/visual/tracking-accuracy/multiple-targets',
  '/ja/drills/visual/tracking-accuracy/pursuit-tracker',
  '/ja/drills/visual/visual-recognition/entropic-grid',
  '/ja/drills/visual/visual-recognition/rhythm-anomaly',
  '/ja/drills/visual/visual-recognition/visual-search',
  '/ko',
  '/ko/drills',
  '/ko/drills/cognitive',
  '/ko/drills/cognitive/attention/concentration-stamina',
  '/ko/drills/cognitive/attention/divided-attention',
  '/ko/drills/cognitive/attention/multi-tasking',
  '/ko/drills/cognitive/focus/concentration-grid',
  '/ko/drills/cognitive/focus/distraction-fighter',
  '/ko/drills/cognitive/processing-speed/reaction-time',
  '/ko/drills/cognitive/processing-speed/rsvp-reader',
  '/ko/drills/cognitive/processing-speed/symbol-matching',
  '/ko/drills/fps',
  '/ko/drills/fps/180-degree-awareness',
  '/ko/drills/fps/angle-hold-trainer',
  '/ko/drills/fps/anti-strafe-jitter-duel',
  '/ko/drills/fps/anti-zigzag-movement-trainer',
  '/ko/drills/fps/flick-shot-training',
  '/ko/drills/fps/flow-state',
  '/ko/drills/fps/instant-response',
  '/ko/drills/fps/micro-correction-precision',
  '/ko/drills/fps/pro-smooth-pursuit',
  '/ko/drills/fps/recoil-control',
  '/ko/drills/fps/strafe-tracking',
  '/ko/drills/fps/target-acquisition',
  '/ko/drills/fps/target-prioritization',
  '/ko/drills/fps/target-switching-swarm',
  '/ko/drills/fps/vertical-air-track',
  '/ko/drills/memory',
  '/ko/drills/memory/short-term-memory/color-sequence',
  '/ko/drills/memory/short-term-memory/digit-span',
  '/ko/drills/memory/short-term-memory/word-recall',
  '/ko/drills/memory/spatial-memory/grid-memorization',
  '/ko/drills/memory/spatial-memory/object-location',
  '/ko/drills/memory/spatial-memory/path-tracing',
  '/ko/drills/memory/working-memory/n-back',
  '/ko/drills/motor',
  '/ko/drills/motor/hand-eye-coordination/aim-trainer',
  '/ko/drills/motor/hand-eye-coordination/drag-and-drop',
  '/ko/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/ko/drills/motor/movement-speed/finger-sequencing',
  '/ko/drills/motor/movement-speed/keyboard-recognition',
  '/ko/drills/motor/movement-speed/rapid-tapping',
  '/ko/drills/motor/precision-control/steady-hand',
  '/ko/drills/motor/precision-control/tracing',
  '/ko/drills/physical',
  '/ko/drills/physical/balance-training/stability-challenge',
  '/ko/drills/physical/coordination/complex-pattern',
  '/ko/drills/physical/coordination/cross-body-movement',
  '/ko/drills/physical/coordination/dynamic-grid-evasion',
  '/ko/drills/physical/fitness/agility-ladder',
  '/ko/drills/physical/fitness/jump-sequence',
  '/ko/drills/physical/fitness/speed-drill',
  '/ko/drills/physical/reflex-training/drop-catch',
  '/ko/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/ko/drills/physical/reflex-training/quick-dodge',
  '/ko/drills/physical/reflex-training/reaction-chain',
  '/ko/drills/reaction-speed',
  '/ko/drills/reaction-speed/reaction-time-test',
  '/ko/drills/reaction-speed/saccadic-gallery',
  '/ko/drills/visual',
  '/ko/drills/visual-tracking',
  '/ko/drills/visual-tracking/directional-chaos-pursuit',
  '/ko/drills/visual-tracking/dynamic-evasion-pursuit',
  '/ko/drills/visual-tracking/ghosting-suppress-pursuit',
  '/ko/drills/visual-tracking/infinity-pursuit',
  '/ko/drills/visual-tracking/momentum-teleport-pursuit',
  '/ko/drills/visual-tracking/peripheral-ping-pursuit',
  '/ko/drills/visual-tracking/predictive-pursuit',
  '/ko/drills/visual-tracking/sine-wave-pursuit',
  '/ko/drills/visual-tracking/spatial-shift-pursuit',
  '/ko/drills/visual-tracking/split-screen-tracking',
  '/ko/drills/visual-tracking/staircase-step',
  '/ko/drills/visual-tracking/strobe-prediction-pursuit',
  '/ko/drills/visual-tracking/triangular-pursuit',
  '/ko/drills/visual-tracking/zig-zag-path-pursuit',
  '/ko/drills/visual/depth-perception/distance-judgment',
  '/ko/drills/visual/reaction-speed/go/no-go',
  '/ko/drills/visual/reaction-speed/light-reaction',
  '/ko/drills/visual/tracking-accuracy/moving-target',
  '/ko/drills/visual/tracking-accuracy/multiple-targets',
  '/ko/drills/visual/tracking-accuracy/pursuit-tracker',
  '/ko/drills/visual/visual-recognition/entropic-grid',
  '/ko/drills/visual/visual-recognition/rhythm-anomaly',
  '/ko/drills/visual/visual-recognition/visual-search',
  '/pt/drills',
  '/pt/drills/cognitive/attention/concentration-stamina',
  '/pt/drills/cognitive/attention/divided-attention',
  '/pt/drills/cognitive/attention/multi-tasking',
  '/pt/drills/cognitive/focus/concentration-grid',
  '/pt/drills/cognitive/focus/distraction-fighter',
  '/pt/drills/cognitive/processing-speed/reaction-time',
  '/pt/drills/cognitive/processing-speed/rsvp-reader',
  '/pt/drills/cognitive/processing-speed/symbol-matching',
  '/pt/drills/fps',
  '/pt/drills/fps/180-degree-awareness',
  '/pt/drills/fps/angle-hold-trainer',
  '/pt/drills/fps/anti-strafe-jitter-duel',
  '/pt/drills/fps/anti-zigzag-movement-trainer',
  '/pt/drills/fps/flick-shot-training',
  '/pt/drills/fps/flow-state',
  '/pt/drills/fps/instant-response',
  '/pt/drills/fps/micro-correction-precision',
  '/pt/drills/fps/pro-smooth-pursuit',
  '/pt/drills/fps/recoil-control',
  '/pt/drills/fps/strafe-tracking',
  '/pt/drills/fps/target-acquisition',
  '/pt/drills/fps/target-prioritization',
  '/pt/drills/fps/target-switching-swarm',
  '/pt/drills/fps/vertical-air-track',
  '/pt/drills/memory/short-term-memory/color-sequence',
  '/pt/drills/memory/short-term-memory/digit-span',
  '/pt/drills/memory/short-term-memory/word-recall',
  '/pt/drills/memory/spatial-memory/grid-memorization',
  '/pt/drills/memory/spatial-memory/object-location',
  '/pt/drills/memory/spatial-memory/path-tracing',
  '/pt/drills/memory/working-memory/n-back',
  '/pt/drills/motor',
  '/pt/drills/motor/hand-eye-coordination/aim-trainer',
  '/pt/drills/motor/hand-eye-coordination/precision-flick-shot',
  '/pt/drills/motor/movement-speed/finger-sequencing',
  '/pt/drills/motor/movement-speed/keyboard-recognition',
  '/pt/drills/motor/movement-speed/rapid-tapping',
  '/pt/drills/motor/precision-control/steady-hand',
  '/pt/drills/motor/precision-control/tracing',
  '/pt/drills/physical',
  '/pt/drills/physical/balance-training/stability-challenge',
  '/pt/drills/physical/coordination/complex-pattern',
  '/pt/drills/physical/coordination/cross-body-movement',
  '/pt/drills/physical/coordination/dynamic-grid-evasion',
  '/pt/drills/physical/fitness/agility-ladder',
  '/pt/drills/physical/fitness/jump-sequence',
  '/pt/drills/physical/fitness/speed-drill',
  '/pt/drills/physical/reflex-training/drop-catch',
  '/pt/drills/physical/reflex-training/peripheral-threat-sweeper',
  '/pt/drills/physical/reflex-training/quick-dodge',
  '/pt/drills/physical/reflex-training/reaction-chain',
  '/pt/drills/reaction-speed/reaction-time-test',
  '/pt/drills/reaction-speed/saccadic-gallery',
  '/pt/drills/visual',
  '/pt/drills/visual-tracking',
  '/pt/drills/visual-tracking/directional-chaos-pursuit',
  '/pt/drills/visual-tracking/dynamic-evasion-pursuit',
  '/pt/drills/visual-tracking/ghosting-suppress-pursuit',
  '/pt/drills/visual-tracking/infinity-pursuit',
  '/pt/drills/visual-tracking/momentum-teleport-pursuit',
  '/pt/drills/visual-tracking/peripheral-ping-pursuit',
  '/pt/drills/visual-tracking/predictive-pursuit',
  '/pt/drills/visual-tracking/sine-wave-pursuit',
  '/pt/drills/visual-tracking/spatial-shift-pursuit',
  '/pt/drills/visual-tracking/split-screen-tracking',
  '/pt/drills/visual-tracking/staircase-step',
  '/pt/drills/visual-tracking/strobe-prediction-pursuit',
  '/pt/drills/visual-tracking/triangular-pursuit',
  '/pt/drills/visual-tracking/zig-zag-path-pursuit',
  '/pt/drills/visual/depth-perception/distance-judgment',
  '/pt/drills/visual/reaction-speed/light-reaction',
  '/pt/drills/visual/tracking-accuracy/moving-target',
  '/pt/drills/visual/tracking-accuracy/multiple-targets',
  '/pt/drills/visual/tracking-accuracy/pursuit-tracker',
  '/pt/drills/visual/visual-recognition/entropic-grid',
  '/pt/drills/visual/visual-recognition/rhythm-anomaly',
];
for (const path of CHANGED_2026_10_08) UPDATED_OVERRIDES[path] = '2026-10-08';


// Ranked by measured Search Console performance, then by realistic potential.
// /drills/fps carries the most non-brand impressions of any page on the site;
// /drills is the strongest converting hub; memory and visual have real query
// demand sitting at page 3-5 and are the clearest upside.
const HUB_PRIORITY = {
  '/drills': 0.9,
  '/drills/fps': 0.9,
  '/drills/memory': 0.8,
  '/drills/visual': 0.8,
  '/drills/cognitive': 0.8,
  '/drills/motor': 0.7,
  '/drills/reaction-speed': 0.7,
  '/drills/physical': 0.7,
  '/drills/visual-tracking': 0.7,
};

// Drill-page priority by category, mirroring where the demand actually is.
const DRILL_PRIORITY = {
  fps: 0.8,
  motor: 0.7,
  memory: 0.7,
  cognitive: 0.6,
  'reaction-speed': 0.6,
  visual: 0.6,
  'visual-tracking': 0.5,
  physical: 0.5,
};

// A handful of drill pages already rank or have measured impressions; they get
// a lift above their category baseline.
const DRILL_PRIORITY_OVERRIDES = {
  '/drills/fps/flick-shot-training': 0.9,
};

const entry = (path, lastModified, changeFrequency, priority, route = path) => {
  const languages = getAlternateLanguages(route);
  return {
    url: `${BASE_URL}${path}`,
    lastModified,
    changeFrequency,
    priority,
    ...(Object.keys(languages).length > 2 && { alternates: { languages } }),
  };
};

export default async function sitemap() {
  const staticEntries = [
    entry('/', UPDATED.home, 'weekly', 1.0),
    entry('/drills', UPDATED.directory, 'weekly', HUB_PRIORITY['/drills']),
    ...Object.keys(HUB_PRIORITY)
      .filter((path) => path !== '/drills')
      .map((path) =>
        entry(
          path,
          UPDATED_OVERRIDES[path] ??
            UPDATED[path.replace('/drills/', '')] ??
            UPDATED.hub,
          'weekly',
          HUB_PRIORITY[path]
        )
      ),
    // About carries the entity description and the measurement methodology, so
    // it ranks above the legal pages: it is the page that answers "who is making
    // this claim", which is what both Google's quality guidance and the answer
    // engines weight when deciding whether to cite a tool site at all.
    entry('/about', UPDATED.legal, 'monthly', 0.5),
    // Low priority but genuinely indexable, and a site with no reachable legal
    // pages reads as low-trust to both search engines and users.
    entry('/privacy', UPDATED.privacy, 'yearly', 0.3),
    entry('/terms', UPDATED.legal, 'yearly', 0.3),
    entry('/delete-account', UPDATED.privacy, 'yearly', 0.3),
  ];

  // Rule 1 applied to the locale trees: derive them from LOCALIZED_ROUTES
  // rather than restating 55 URLs by hand, so a route that exists under
  // app/pt but not app/ko (or vice versa) cannot silently ship as a 404 in
  // the sitemap. LOCALIZED_ROUTES is the same list the language switcher and
  // the header search resolve against.
const LOCALIZED_PRIORITY = {
    '/': 0.9,
    '/drills': 0.9,
    '/drills/fps': 0.9,
    '/drills/motor/movement-speed/rapid-tapping': 0.9,
    '/drills/reaction-speed/reaction-time-test': 0.9,
    '/drills/reaction-speed/reflex-training-drill': 0.85,
  };
  const localizedEntries = LOCALES
    .filter((loc) => loc !== DEFAULT_LOCALE)
    .flatMap((loc) =>
      LOCALIZED_ROUTES
        .filter((route) => hasLocalizedRoute(loc, route))
        .map((route) =>
          entry(
            localeUrl(loc, route),
            UPDATED_OVERRIDES[localeUrl(loc, route)] ?? UPDATED_OVERRIDES[route] ?? UPDATED.localized,
            'weekly',
            LOCALIZED_PRIORITY[route] ?? 0.8,
            route
          )
        )
    );

  const drillEntries = DRILLS.map((drill) =>
    entry(
      drill.href,
      UPDATED_OVERRIDES[drill.href] ?? UPDATED[drill.category] ?? UPDATED.drill,
      'monthly',
      DRILL_PRIORITY_OVERRIDES[drill.href] ?? DRILL_PRIORITY[drill.category] ?? 0.5
    )
  );

  return [...staticEntries, ...localizedEntries, ...drillEntries];
}
