// Lean nav-only slice of lib/drillsRegistry.js — id/name/href/category/etc,
// no description/keywords (~35KB of SEO copy text). For components that render
// navigation, breadcrumbs, or cross-links but never SEO copy: SiteHeader,
// SiteFooter, DrillBreadcrumb, RelatedDrills. Keeping this data out of their
// bundle matters because they're mounted on every page site-wide.
//
// Generated from lib/drillsRegistry.js — if a drill is added/renamed/moved
// there, regenerate this file (map DRILLS to the same field subset) rather
// than hand-editing it out of sync.

export const DESKTOP_ONLY_CATEGORIES = ['fps', 'physical', 'motor'];

export const DRILLS = [
  {
    "id": "cognitive-concentration-stamina",
    "name": "Concentration Stamina",
    "folderName": "concentration-stamina",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/concentration-stamina",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "cognitive-divided-attention",
    "name": "Divided Attention Test",
    "folderName": "divided-attention",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/divided-attention",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "cognitive-multi-tasking",
    "name": "Multitasking Test",
    "folderName": "multi-tasking",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/multi-tasking",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "cognitive-concentration-grid",
    "name": "Schulte Table Trainer",
    "folderName": "concentration-grid",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Focus & Concentration",
    "href": "/drills/cognitive/focus/concentration-grid",
    "difficulty": "Intermediate",
    "duration": "45s"
  },
  {
    "id": "cognitive-distraction-fighter",
    "name": "Distraction Fighter",
    "folderName": "distraction-fighter",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Focus & Concentration",
    "href": "/drills/cognitive/focus/distraction-fighter",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "cognitive-reaction-time",
    "name": "Reaction Time",
    "folderName": "reaction-time",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/reaction-time",
    "difficulty": "Beginner",
    "duration": "45s+"
  },
  {
    "id": "cognitive-rsvp-reader",
    "name": "RSVP Speed Reader",
    "folderName": "rsvp-reader",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/rsvp-reader",
    "difficulty": "Intermediate",
    "duration": "45s"
  },
  {
    "id": "cognitive-symbol-matching",
    "name": "Symbol Matching",
    "folderName": "symbol-matching",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/symbol-matching",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-180-degree-awareness",
    "name": "180° Awareness Pro",
    "folderName": "180-degree-awareness",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/180-degree-awareness",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "fps-angle-hold-trainer",
    "name": "Crosshair Placement & Angle Hold Trainer",
    "folderName": "angle-hold-trainer",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Movement & Recoil",
    "href": "/drills/fps/angle-hold-trainer",
    "difficulty": "Expert",
    "duration": "45s+"
  },
  {
    "id": "fps-anti-strafe-jitter-duel",
    "name": "Anti-Strafe Jitter Trainer",
    "folderName": "anti-strafe-jitter-duel",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/anti-strafe-jitter-duel",
    "difficulty": "Expert",
    "duration": "45s+"
  },
  {
    "id": "fps-anti-zigzag-movement-trainer",
    "name": "Anti-Zigzag Aim Trainer",
    "folderName": "anti-zigzag-movement-trainer",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/anti-zigzag-movement-trainer",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-flick-shot-training",
    "name": "Flick Shot Trainer",
    "folderName": "flick-shot-training",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/flick-shot-training",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "fps-flow-state",
    "name": "Flow State Trainer",
    "folderName": "flow-state",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/flow-state",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "fps-instant-response",
    "name": "FPS Reaction Time Test",
    "folderName": "instant-response",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/instant-response",
    "difficulty": "Beginner",
    "duration": "45s+"
  },
  {
    "id": "fps-micro-correction-precision",
    "name": "Micro-Correction Aim Trainer",
    "folderName": "micro-correction-precision",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/micro-correction-precision",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-pro-smooth-pursuit",
    "name": "Smooth Pursuit Aim Trainer",
    "folderName": "pro-smooth-pursuit",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/pro-smooth-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-recoil-control",
    "name": "Recoil Control Trainer",
    "folderName": "recoil-control",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Movement & Recoil",
    "href": "/drills/fps/recoil-control",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-strafe-tracking",
    "name": "Strafe Tracking Aim Trainer",
    "folderName": "strafe-tracking",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/strafe-tracking",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-target-acquisition",
    "name": "Target Acquisition Aim Trainer",
    "folderName": "target-acquisition",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-acquisition",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "fps-target-prioritization",
    "name": "Target Prioritization Aim Trainer",
    "folderName": "target-prioritization",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-prioritization",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-target-switching-swarm",
    "name": "Target Switching Aim Trainer",
    "folderName": "target-switching-swarm",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-switching-swarm",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "fps-vertical-air-track",
    "name": "Vertical Aim Trainer",
    "folderName": "vertical-air-track",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/vertical-air-track",
    "difficulty": "Expert",
    "duration": "45s+"
  },
  {
    "id": "memory-color-sequence",
    "name": "Color Memory Game",
    "folderName": "color-sequence",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/color-sequence",
    "difficulty": "Easy",
    "duration": "45s"
  },
  {
    "id": "memory-digit-span",
    "name": "Digit Span",
    "folderName": "digit-span",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/digit-span",
    "difficulty": "Easy",
    "duration": "45s"
  },
  {
    "id": "memory-word-recall",
    "name": "Word Recall",
    "folderName": "word-recall",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/word-recall",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "memory-grid-memorization",
    "name": "Grid Memorization",
    "folderName": "grid-memorization",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/grid-memorization",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "memory-object-location",
    "name": "Object Location",
    "folderName": "object-location",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/object-location",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "memory-path-tracing",
    "name": "Path Tracing",
    "folderName": "path-tracing",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/path-tracing",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "memory-n-back",
    "name": "3-Back Training",
    "folderName": "n-back",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Working Memory",
    "href": "/drills/memory/working-memory/n-back",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "motor-aim-trainer",
    "name": "Aim Trainer",
    "folderName": "aim-trainer",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/aim-trainer",
    "difficulty": "Hard",
    "duration": "45s+"
  },
  {
    "id": "motor-drag-and-drop",
    "name": "Drag and Drop Test",
    "folderName": "drag-and-drop",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/drag-and-drop",
    "difficulty": "Easy",
    "duration": "45s"
  },
  {
    "id": "motor-precision-flick-shot",
    "name": "Precision Flick Shot",
    "folderName": "precision-flick-shot",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/precision-flick-shot",
    "difficulty": "Hard",
    "duration": "45s+"
  },
  {
    "id": "motor-finger-sequencing",
    "name": "Sequence Aim Trainer",
    "folderName": "finger-sequencing",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/finger-sequencing",
    "difficulty": "Medium",
    "duration": "45s+"
  },
  {
    "id": "motor-keyboard-recognition",
    "name": "Keyboard Speed Test",
    "folderName": "keyboard-recognition",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/keyboard-recognition",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "motor-rapid-tapping",
    "name": "CPS Test",
    "folderName": "rapid-tapping",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/rapid-tapping",
    "difficulty": "Easy",
    "duration": "45s"
  },
  {
    "id": "motor-steady-hand",
    "name": "Steady Hand Game",
    "folderName": "steady-hand",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Precision Control",
    "href": "/drills/motor/precision-control/steady-hand",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "motor-tracing",
    "name": "Mouse Tracing Game",
    "folderName": "tracing",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Precision Control",
    "href": "/drills/motor/precision-control/tracing",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "physical-stability-challenge",
    "name": "Stability Challenge",
    "folderName": "stability-challenge",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Balance Training",
    "href": "/drills/physical/balance-training/stability-challenge",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "physical-complex-pattern",
    "name": "Complex Pattern",
    "folderName": "complex-pattern",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/complex-pattern",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "physical-cross-body-movement",
    "name": "Cross Body Movement",
    "folderName": "cross-body-movement",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/cross-body-movement",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "physical-dynamic-grid-evasion",
    "name": "Dynamic Grid Evasion",
    "folderName": "dynamic-grid-evasion",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/dynamic-grid-evasion",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "physical-agility-ladder",
    "name": "Agility Ladder",
    "folderName": "agility-ladder",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/agility-ladder",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "physical-jump-sequence",
    "name": "Jump Sequence",
    "folderName": "jump-sequence",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/jump-sequence",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "physical-speed-drill",
    "name": "Speed Drill",
    "folderName": "speed-drill",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/speed-drill",
    "difficulty": "Medium",
    "duration": "45s+"
  },
  {
    "id": "physical-drop-catch",
    "name": "Drop Catch",
    "folderName": "drop-catch",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/drop-catch",
    "difficulty": "Easy",
    "duration": "45s+"
  },
  {
    "id": "physical-peripheral-threat-sweeper",
    "name": "Peripheral Threat Sweeper",
    "folderName": "peripheral-threat-sweeper",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/peripheral-threat-sweeper",
    "difficulty": "Hard",
    "duration": "45s+"
  },
  {
    "id": "physical-quick-dodge",
    "name": "Quick Dodge",
    "folderName": "quick-dodge",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/quick-dodge",
    "difficulty": "Medium",
    "duration": "45s"
  },
  {
    "id": "physical-reaction-chain",
    "name": "Reaction Chain",
    "folderName": "reaction-chain",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/reaction-chain",
    "difficulty": "Hard",
    "duration": "45s"
  },
  {
    "id": "reaction-speed-barrier-sequence-pursuit",
    "name": "Jiggle Peek Trainer",
    "folderName": "barrier-sequence-pursuit",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/barrier-sequence-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-fps-tracking-trainer",
    "name": "FPS Tracking Trainer",
    "folderName": "fps-tracking-trainer",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/fps-tracking-trainer",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-market-doors-pursuit",
    "name": "Corner Checking Trainer",
    "folderName": "market-doors-pursuit",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/market-doors-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-reaction-game",
    "name": "Reaction Game",
    "folderName": "reaction-game",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reaction-game",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-reaction-time-test",
    "name": "Stop the Timer Game",
    "folderName": "reaction-time-test",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reaction-time-test",
    "difficulty": "Beginner",
    "duration": "45s"
  },
  {
    "id": "reaction-speed-reflex-training-drill",
    "name": "Reflex Training Drill",
    "folderName": "reflex-training-drill",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reflex-training-drill",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-saccadic-gallery",
    "name": "Saccadic Eye Exercises",
    "folderName": "saccadic-gallery",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/saccadic-gallery",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "reaction-speed-visual-tracking-speed-test",
    "name": "Visual Tracking Speed Test",
    "folderName": "visual-tracking-speed-test",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/visual-tracking-speed-test",
    "difficulty": "Advanced",
    "duration": "45s+"
  },
  {
    "id": "visual-distance-judgment",
    "name": "Depth Perception Test",
    "folderName": "distance-judgment",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "depth-perception",
    "href": "/drills/visual/depth-perception/distance-judgment",
    "difficulty": "Intermediate",
    "duration": "45s"
  },
  {
    "id": "visual-no-go",
    "name": "Chroma-Sync Lab",
    "folderName": "no-go",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "reaction-speed",
    "href": "/drills/visual/reaction-speed/go/no-go",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "visual-light-reaction",
    "name": "Strobe-Latency Lab",
    "folderName": "light-reaction",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "reaction-speed",
    "href": "/drills/visual/reaction-speed/light-reaction",
    "difficulty": "Beginner",
    "duration": "45s+"
  },
  {
    "id": "visual-moving-target",
    "name": "Kinetic Intercept",
    "folderName": "moving-target",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/moving-target",
    "difficulty": "Intermediate",
    "duration": "45s+"
  },
  {
    "id": "visual-multiple-targets",
    "name": "Ghost-Link Tracking",
    "folderName": "multiple-targets",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/multiple-targets",
    "difficulty": "Expert",
    "duration": "15-60s"
  },
  {
    "id": "visual-pursuit-tracker",
    "name": "Auto-Pursuit",
    "folderName": "pursuit-tracker",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/pursuit-tracker",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "visual-entropic-grid",
    "name": "Entropic Grid",
    "folderName": "entropic-grid",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/entropic-grid",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "visual-rhythm-anomaly",
    "name": "Rhythm Anomaly",
    "folderName": "rhythm-anomaly",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/rhythm-anomaly",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "visual-visual-search",
    "name": "Visual Search",
    "folderName": "visual-search",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/visual-search",
    "difficulty": "Advanced",
    "duration": "45s"
  },
  {
    "id": "visual-tracking-constant-slow-pursuit",
    "name": "Constant Slow Pursuit",
    "folderName": "constant-slow-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/constant-slow-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-directional-chaos-pursuit",
    "name": "Directional Chaos Pursuit",
    "folderName": "directional-chaos-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/directional-chaos-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-dynamic-evasion-pursuit",
    "name": "Dynamic Evasion Pursuit",
    "folderName": "dynamic-evasion-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/dynamic-evasion-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-ghosting-suppress-pursuit",
    "name": "Ghosting Suppress Pursuit",
    "folderName": "ghosting-suppress-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/ghosting-suppress-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-infinity-pursuit",
    "name": "Infinity Pursuit",
    "folderName": "infinity-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/infinity-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-momentum-teleport-pursuit",
    "name": "Momentum Teleport Pursuit",
    "folderName": "momentum-teleport-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/momentum-teleport-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-peripheral-ping-pursuit",
    "name": "Peripheral Ping Pursuit",
    "folderName": "peripheral-ping-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/peripheral-ping-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-predictive-pursuit",
    "name": "Predictive Pursuit",
    "folderName": "predictive-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/predictive-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-sine-wave-pursuit",
    "name": "Sine-Wave Pursuit",
    "folderName": "sine-wave-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/sine-wave-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-spatial-shift-pursuit",
    "name": "Spatial-Shift Pursuit",
    "folderName": "spatial-shift-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/spatial-shift-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-split-screen-tracking",
    "name": "Split-Screen Tracking",
    "folderName": "split-screen-tracking",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/split-screen-tracking",
    "difficulty": "Intermediate",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-staircase-step",
    "name": "Vertical Tracking",
    "folderName": "staircase-step",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/staircase-step",
    "difficulty": "Intermediate",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-strobe-prediction-pursuit",
    "name": "Strobe Prediction Pursuit",
    "folderName": "strobe-prediction-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/strobe-prediction-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-triangular-pursuit",
    "name": "Triangular Pursuit",
    "folderName": "triangular-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/triangular-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s"
  },
  {
    "id": "visual-tracking-zig-zag-path-pursuit",
    "name": "Zig-Zag Path Pursuit",
    "folderName": "zig-zag-path-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/zig-zag-path-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s"
  }
];
