// Centralized Drill Registry - Single Source of Truth for all 81 drills
export const DESKTOP_ONLY_CATEGORIES = ['fps', 'physical', 'motor'];

export const DRILLS = [
  {
    "id": "cognitive-concentration-stamina",
    "name": "Concentration Stamina",
    "folderName": "concentration-stamina",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/concentration-stamina",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "Rule-switching endurance: alternate between VOWELS and PRIMES every 10 seconds",
    "keywords": [
      "alternate",
      "attention",
      "attention span test",
      "between",
      "cognitive",
      "concentration",
      "continuous performance test",
      "drills",
      "endurance",
      "every",
      "focus test",
      "primes",
      "rule",
      "seconds",
      "stamina",
      "switching",
      "training",
      "vowels"
    ]
  },
  {
    "id": "cognitive-divided-attention",
    "name": "Divided Attention Test",
    "folderName": "divided-attention",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/divided-attention",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Dual-task training: track moving balls while matching even numbers simultaneously",
    "keywords": [
      "attention",
      "balls",
      "cognitive",
      "divided",
      "drills",
      "dual",
      "even",
      "matching",
      "moving",
      "numbers",
      "simultaneously",
      "task",
      "track",
      "training",
      "while"
    ]
  },
  {
    "id": "cognitive-multi-tasking",
    "name": "Multitasking Test",
    "folderName": "multi-tasking",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Attention Training",
    "href": "/drills/cognitive/attention/multi-tasking",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Juggle multiple cognitive tasks simultaneously with increasing complexity",
    "keywords": [
      "attention",
      "cognitive",
      "complexity",
      "drills",
      "increasing",
      "juggle",
      "multi",
      "multiple",
      "simultaneously",
      "tasking",
      "tasks",
      "training"
    ]
  },
  {
    "id": "cognitive-concentration-grid",
    "name": "Schulte Table Trainer",
    "folderName": "concentration-grid",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Focus & Concentration",
    "href": "/drills/cognitive/focus/concentration-grid",
    "difficulty": "Intermediate",
    "duration": "45s",
    "description": "Sequential search: find numbers on expanding 3x3 to 8x8 grids with level bonuses",
    "keywords": [
      "concentration grid",
      "the concentration grid",
      "concentration grids",
      "concentration grid online",
      "schulte table",
      "schulte table online",
      "schulte table trainer",
      "schulte grid",
      "tabla de schulte",
      "tabela de schulte",
      "シュルテテーブル",
      "peripheral vision training",
      "visual search speed",
      "sequential number search",
      "focus training game",
      "3x3",
      "8x8",
      "cognitive",
      "concentration",
      "focus",
      "grid",
      "numbers"
    ]
  },
  {
    "id": "cognitive-distraction-fighter",
    "name": "Distraction Fighter",
    "folderName": "distraction-fighter",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Focus & Concentration",
    "href": "/drills/cognitive/focus/distraction-fighter",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Stroop test: identify ink colors while ignoring conflicting word meanings",
    "keywords": [
      "cognitive",
      "colors",
      "concentration",
      "conflicting",
      "distraction",
      "drills",
      "fighter",
      "focus",
      "identify",
      "ignoring",
      "ink",
      "meanings",
      "stroop",
      "test",
      "while",
      "word"
    ]
  },
  {
    "id": "cognitive-reaction-time",
    "name": "Reaction Time",
    "folderName": "reaction-time",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/reaction-time",
    "difficulty": "Beginner",
    "duration": "45s+",
    "description": "Neuro-switch: click RED targets only, ignore BLUE - targets reposition every 950ms",
    "keywords": [
      "950ms",
      "blue",
      "click",
      "cognitive",
      "drills",
      "every",
      "ignore",
      "neuro",
      "only",
      "processing",
      "reaction",
      "red",
      "reposition",
      "speed",
      "switch",
      "targets",
      "time"
    ]
  },
  {
    "id": "cognitive-rsvp-reader",
    "name": "RSVP Speed Reader",
    "folderName": "rsvp-reader",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/rsvp-reader",
    "difficulty": "Intermediate",
    "duration": "45s",
    "description": "Rapid serial visual presentation: flash words at the Optimal Recognition Point, 100-1000 WPM",
    "keywords": [
      "100",
      "1000",
      "cognitive",
      "drills",
      "flash",
      "optimal",
      "point",
      "presentation",
      "processing",
      "rapid",
      "reader",
      "recognition",
      "rsvp",
      "serial",
      "speed",
      "visual",
      "words",
      "wpm"
    ]
  },
  {
    "id": "cognitive-symbol-matching",
    "name": "Symbol Matching",
    "folderName": "symbol-matching",
    "category": "cognitive",
    "categoryLabel": "Cognitive Drills",
    "subcategory": "Processing Speed",
    "href": "/drills/cognitive/processing-speed/symbol-matching",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Cognitive flexibility: match Greek symbols to numbers with keys that change every answer",
    "keywords": [
      "answer",
      "change",
      "cognitive",
      "drills",
      "every",
      "flexibility",
      "greek",
      "keys",
      "match",
      "matching",
      "numbers",
      "processing",
      "speed",
      "symbol",
      "symbols",
      "that"
    ]
  },
  {
    "id": "fps-180-degree-awareness",
    "name": "180° Awareness Pro",
    "folderName": "180-degree-awareness",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/180-degree-awareness",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Targets spawn at extreme screen edges with progressive difficulty and streak heat",
    "keywords": [
      "180도 화면전환",
      "180도 에임",
      "180도 플릭",
      "180度 フリック",
      "振り向き 練習 FPS",
      "180度 振り向き 練習",
      "180 flick drill",
      "snap turn aim trainer",
      "180 flick aim trainer",
      "180 aim trainer",
      "180",
      "250ms",
      "awareness",
      "degree",
      "edges",
      "every",
      "extreme",
      "fps",
      "lives",
      "peripheral",
      "reflex",
      "scan",
      "screen",
      "spawn",
      "system",
      "targets",
      "training"
    ]
  },
  {
    "id": "fps-angle-hold-trainer",
    "name": "Crosshair Placement & Angle Hold Trainer",
    "folderName": "angle-hold-trainer",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Movement & Recoil",
    "href": "/drills/fps/angle-hold-trainer",
    "difficulty": "Expert",
    "duration": "45s+",
    "description": "Train reaction times and crosshair placement against cover peeking, wide swings, and jiggle movements",
    "keywords": [
      "against",
      "angle",
      "cover",
      "crosshair",
      "fps",
      "hold",
      "jiggle",
      "movement",
      "movements",
      "peek",
      "peeking",
      "placement",
      "reaction",
      "recoil",
      "swings",
      "times",
      "trainer",
      "training",
      "wide"
    ]
  },
  {
    "id": "fps-anti-strafe-jitter-duel",
    "name": "Anti-Strafe Jitter Trainer",
    "folderName": "anti-strafe-jitter-duel",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/anti-strafe-jitter-duel",
    "difficulty": "Expert",
    "duration": "45s+",
    "description": "Erratic close-range tracking simulator mimicking human ADAD strafes with high-rate physics jitter",
    "keywords": [
      "ADAD 무빙 연습",
      "무빙 트래킹 에임 연습",
      "ジッターエイム 練習",
      "トラッキング エイム 練習",
      "レレレ撃ち 練習",
      "adad strafe practice",
      "reactive tracking aim trainer",
      "jitter aim trainer",
      "anti strafe jitter trainer",
      "adad",
      "anti",
      "close",
      "duel",
      "erratic",
      "fps",
      "high",
      "human",
      "jitter",
      "mimicking",
      "physics",
      "range",
      "rate",
      "simulator",
      "strafe",
      "strafes",
      "strafing",
      "switching",
      "tracking",
      "training"
    ]
  },
  {
    "id": "fps-anti-zigzag-movement-trainer",
    "name": "Anti-Zigzag Aim Trainer",
    "folderName": "anti-zigzag-movement-trainer",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/anti-zigzag-movement-trainer",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Track evasive human-like targets executing aggressive zig-zag strafing, pauses, jumps, slides, and fake-outs.",
    "keywords": [
      "슬라이딩 캔슬 트래킹",
      "지그재그 에임 연습",
      "지그재그 무빙 트래킹",
      "ジグザグ エイム 練習",
      "スライディング トラッキング",
      "ジグザグ移動 練習",
      "evasive strafe tracking",
      "zigzag aim trainer",
      "anti zigzag movement trainer",
      "anti-zigzag aim trainer",
      "aggressive",
      "anti",
      "evasive",
      "executing",
      "fake",
      "fps",
      "human",
      "jumps",
      "like",
      "movement",
      "outs",
      "pauses",
      "slides",
      "strafing",
      "switching",
      "targets",
      "track",
      "tracking",
      "trainer",
      "training",
      "zag",
      "zig",
      "zigzag"
    ]
  },
  {
    "id": "fps-flick-shot-training",
    "name": "Flick Shot Trainer",
    "folderName": "flick-shot-training",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/flick-shot-training",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "One-tap flick shots with adaptive target windows (150-1000ms) and timer ring feedback",
    "keywords": [
      "flick shot trainer",
      "flick aim trainer",
      "フリック エイム 練習",
      "フリック エイム",
      "플릭샷 연습",
      "플릭 에임",
      "1000ms",
      "150",
      "adaptive",
      "clicking",
      "feedback",
      "flick",
      "fps",
      "one",
      "precision",
      "ring",
      "shot",
      "shots",
      "tap",
      "target",
      "timer",
      "training",
      "windows"
    ]
  },
  {
    "id": "fps-flow-state",
    "name": "Flow State Trainer",
    "folderName": "flow-state",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/flow-state",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Continuous aim flow state practice. Maintain rhythm across sequential spawning targets.",
    "keywords": [
      "FPS 몰입 훈련",
      "몰입 에임 트레이너",
      "플로우 상태 에임 연습",
      "ゾーン エイム 練習",
      "FPS 集中力 トレーニング",
      "フロー状態 エイム 練習",
      "rhythm aim trainer",
      "fps flow state",
      "flow state trainer",
      "flow state aim trainer",
      "across",
      "aim",
      "awareness",
      "continuous",
      "flow",
      "fps",
      "maintain",
      "practice",
      "reflex",
      "rhythm",
      "sequential",
      "spawning",
      "state",
      "targets",
      "training"
    ]
  },
  {
    "id": "fps-instant-response",
    "name": "FPS Reaction Time Test",
    "folderName": "instant-response",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Reflex & Awareness",
    "href": "/drills/fps/instant-response",
    "difficulty": "Beginner",
    "duration": "45s+",
    "description": "Center-flash targets at random 0.8-2.5s with 80-1200ms adaptive window",
    "keywords": [
      "에임 반응속도 측정",
      "FPS 반응속도 테스트",
      "反応速度 テスト FPS",
      "FPS 反応速度 テスト",
      "fps reflex training",
      "click response time",
      "gaming reflex test",
      "fps reaction time test",
      "1200ms",
      "adaptive",
      "awareness",
      "center",
      "flash",
      "fps",
      "instant",
      "random",
      "reflex",
      "response",
      "targets",
      "test",
      "training",
      "window"
    ]
  },
  {
    "id": "fps-micro-correction-precision",
    "name": "Micro-Correction Aim Trainer",
    "folderName": "micro-correction-precision",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/micro-correction-precision",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Precision micro-correction trainer: hit anchor then snap-click the adjacent micro-target",
    "keywords": [
      "micro-correction aim trainer",
      "micro adjustment aim",
      "マイクロフリック 練習",
      "エイム 微調整",
      "마이크로 플릭",
      "에임 미세조정",
      "adjacent",
      "anchor",
      "click",
      "clicking",
      "correction",
      "fps",
      "hit",
      "micro",
      "precision",
      "snap",
      "target",
      "then",
      "trainer",
      "training"
    ]
  },
  {
    "id": "fps-pro-smooth-pursuit",
    "name": "Smooth Pursuit Aim Trainer",
    "folderName": "pro-smooth-pursuit",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/pro-smooth-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Lissajous curve target at 360Hz refresh. +1pt/1.0s on target. Green when tracked.",
    "keywords": [
      "스무스 퍼슈트 에임",
      "활창 추적 안구 운동 훈련",
      "스무스 트래킹 에임 연습",
      "スムーズ トラッキング 練習",
      "滑走性眼球運動 トレーニング",
      "スムース パシュート エイム",
      "lissajous tracking aim trainer",
      "curve tracking aim trainer",
      "smooth pursuit aim",
      "smooth pursuit aim trainer",
      "1pt",
      "360hz",
      "curve",
      "fps",
      "green",
      "lab",
      "lissajous",
      "pro",
      "pursuit",
      "refresh",
      "smooth",
      "switching",
      "target",
      "tracked",
      "tracking",
      "training",
      "when"
    ]
  },
  {
    "id": "fps-recoil-control",
    "name": "Recoil Control Trainer",
    "folderName": "recoil-control",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Movement & Recoil",
    "href": "/drills/fps/recoil-control",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Esports recoil control spray simulator: pull down mouse to counter spray vertical S-curve",
    "keywords": [
      "스프레이 제어 연습",
      "에이펙스 반동 제어",
      "배틀그라운드 반동 연습",
      "FPS 반동 조절 훈련",
      "반동 제어 연습",
      "リコイル練習",
      "リコイル 制御 練習",
      "recoil control trainer",
      "recoil trainer",
      "recoil control",
      "spray pattern practice",
      "cs2 recoil practice",
      "apex recoil trainer",
      "vertical pull down",
      "control",
      "counter",
      "curve",
      "down",
      "esports",
      "fps",
      "lab",
      "mouse",
      "movement",
      "pull",
      "recoil",
      "simulator",
      "spray",
      "training",
      "vertical"
    ]
  },
  {
    "id": "fps-strafe-tracking",
    "name": "Strafe Tracking Aim Trainer",
    "folderName": "strafe-tracking",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/strafe-tracking",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Maintain cursor lock-on targets executing unpredictable, high-rate strafing maneuvers",
    "keywords": [
      "strafe tracking aim trainer",
      "strafe tracking",
      "strafetrack",
      "reactive tracking aim trainer",
      "counter strafe tracking",
      "apex strafe trainer",
      "smooth tracking aim",
      "에임 트래킹 연습",
      "트래킹 연습 사이트",
      "에임 트래킹",
      "cursor",
      "executing",
      "fps",
      "high",
      "lock",
      "maintain",
      "maneuvers",
      "rate",
      "strafe",
      "strafing",
      "switching",
      "targets",
      "tracking",
      "training",
      "unpredictable"
    ]
  },
  {
    "id": "fps-target-acquisition",
    "name": "Target Acquisition Aim Trainer",
    "folderName": "target-acquisition",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-acquisition",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Click 5 targets in brightness order (opacity 1.0\u21920.4). +1 per set, -1 wrong click.",
    "keywords": [
      "target acquisition trainer",
      "first shot accuracy",
      "ターゲット捕捉 エイム",
      "初弾 エイム 練習",
      "타겟 포착 에임",
      "초탄 에임 연습",
      "acquisition",
      "brightness",
      "click",
      "clicking",
      "control",
      "flick",
      "fps",
      "micro",
      "opacity",
      "order",
      "per",
      "precision",
      "set",
      "target",
      "targets",
      "training",
      "wrong"
    ]
  },
  {
    "id": "fps-target-prioritization",
    "name": "Target Prioritization Aim Trainer",
    "folderName": "target-prioritization",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-prioritization",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Clear targets in order of priority: Red (Critical, high value), Blue (Standard), avoid Yellow decoys",
    "keywords": [
      "target prioritization trainer",
      "threat assessment drill",
      "ターゲット優先度 エイム",
      "優先ターゲット エイム",
      "타겟 우선순위 에임",
      "타겟 식별 에임",
      "avoid",
      "blue",
      "clear",
      "clicking",
      "critical",
      "decoys",
      "fps",
      "high",
      "order",
      "precision",
      "prioritization",
      "priority",
      "red",
      "standard",
      "swarm",
      "target",
      "targets",
      "training",
      "value",
      "yellow"
    ]
  },
  {
    "id": "fps-target-switching-swarm",
    "name": "Target Switching Aim Trainer",
    "folderName": "target-switching-swarm",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Precision Clicking",
    "href": "/drills/fps/target-switching-swarm",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Gridshot speed flick switching: click neon targets as fast as they spawn in a moving dynamic swarm",
    "keywords": [
      "target switching aim trainer",
      "target switching trainer",
      "target switching aim",
      "multi target aim trainer",
      "multi target flick training",
      "ターゲット スイッチング エイム",
      "ターゲットスイッチング",
      "スイッチング エイム",
      "타겟 스위칭 에임",
      "타겟 스위칭",
      "에임 스위칭",
      "click",
      "clicking",
      "dynamic",
      "fast",
      "flick",
      "fps",
      "gridshot",
      "moving",
      "neon",
      "precision",
      "spawn",
      "speed",
      "swarm",
      "switching",
      "target",
      "targets",
      "they",
      "training"
    ]
  },
  {
    "id": "fps-vertical-air-track",
    "name": "Vertical Aim Trainer",
    "folderName": "vertical-air-track",
    "category": "fps",
    "categoryLabel": "FPS Training",
    "subcategory": "Tracking & Switching",
    "href": "/drills/fps/vertical-air-track",
    "difficulty": "Expert",
    "duration": "45s+",
    "description": "Practice vertical and parabolic tracking of targets launched high into air flight paths subject to gravity",
    "keywords": [
      "vertical aim trainer",
      "vertical tracking trainer",
      "vertical aim training",
      "y axis aim trainer",
      "aerial target tracking",
      "垂直 エイム 練習",
      "縦エイム 練習",
      "トラッキング エイム 練習",
      "수직 에임 연습",
      "트래킹 에임 연습",
      "air",
      "flight",
      "fps",
      "gravity",
      "high",
      "into",
      "launched",
      "parabolic",
      "paths",
      "practice",
      "subject",
      "switching",
      "targets",
      "track",
      "tracking",
      "training",
      "vertical"
    ]
  },
  {
    "id": "memory-color-sequence",
    "name": "Color Memory Game",
    "folderName": "color-sequence",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/color-sequence",
    "difficulty": "Easy",
    "duration": "45s",
    "description": "Watch and reproduce expanding Simon color sequences in exact temporal order",
    "keywords": [
      "color",
      "color memory game",
      "color sequence",
      "correct",
      "drills",
      "memory",
      "order",
      "patterns",
      "reproduce",
      "sequence",
      "short",
      "simon game",
      "simon says game",
      "term",
      "visual working memory",
      "watch"
    ]
  },
  {
    "id": "memory-digit-span",
    "name": "Digit Span",
    "folderName": "digit-span",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/digit-span",
    "difficulty": "Easy",
    "duration": "45s",
    "description": "Memorize and recall growing sequences of random digits",
    "keywords": [
      "digit span test",
      "digit span memory test",
      "number memory test",
      "forward digit span",
      "wais digit span test",
      "digit span test online",
      "digit memory test",
      "auditory verbal memory",
      "phonological loop span",
      "short term memory test numbers",
      "test de digitos",
      "teste de digitos",
      "数唱課題",
      "숫자 기억력 테스트",
      "zahlenspanne test",
      "digit",
      "digits",
      "drills",
      "growing",
      "memorize",
      "memory",
      "random",
      "recall",
      "sequences",
      "short",
      "span",
      "term"
    ]
  },
  {
    "id": "memory-word-recall",
    "name": "Word Recall",
    "folderName": "word-recall",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Short-Term Memory",
    "href": "/drills/memory/short-term-memory/word-recall",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Study word lists then type all words you remember",
    "keywords": [
      "verbal memory test",
      "word recall test",
      "word memory test",
      "free recall memory test",
      "verbal working memory test",
      "rey auditory verbal learning test",
      "単語記憶テスト",
      "単語記憶",
      "단어 기억력 테스트",
      "단어 기억 게임",
      "verbales gedächtnis test",
      "wortliste gedächtnis test",
      "test de memoria verbal",
      "teste de memoria verbal",
      "all",
      "drills",
      "lists",
      "memory",
      "recall",
      "remember",
      "short",
      "study",
      "term",
      "then",
      "type",
      "word",
      "words",
      "you"
    ]
  },
  {
    "id": "memory-grid-memorization",
    "name": "Grid Memorization",
    "folderName": "grid-memorization",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/grid-memorization",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Memorize lit cell patterns on 4\u00d74 to 5\u00d75 grids",
    "keywords": [
      "cell",
      "corsi block",
      "drills",
      "grid",
      "grid memory test",
      "grids",
      "lit",
      "memorization",
      "memorize",
      "memory",
      "memory matrix",
      "pattern memory",
      "patterns",
      "spatial",
      "spatial memory test",
      "visual memory",
      "visual memory test"
    ]
  },
  {
    "id": "memory-object-location",
    "name": "Object Location",
    "folderName": "object-location",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/object-location",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Remember where emoji objects are placed on expanding grids",
    "keywords": [
      "object location memory test",
      "spatial memory test",
      "object location test",
      "spatial location memory",
      "visuospatial working memory test",
      "空間記憶テスト",
      "공간 기억력 테스트",
      "räumliches gedächtnis test",
      "test de memoria espacial",
      "teste de memoria espacial",
      "are",
      "drills",
      "emoji",
      "expanding",
      "grids",
      "location",
      "memory",
      "object",
      "objects",
      "placed",
      "remember",
      "spatial",
      "where"
    ]
  },
  {
    "id": "memory-path-tracing",
    "name": "Path Tracing",
    "folderName": "path-tracing",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Spatial Memory",
    "href": "/drills/memory/spatial-memory/path-tracing",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Watch animated dot paths then retrace in exact order",
    "keywords": [
      "sequence memory test",
      "path tracing memory test",
      "corsi block tapping test",
      "spatial sequence memory",
      "corsi block test online",
      "順番記憶テスト",
      "コルシブロックテスト",
      "순서 기억 테스트",
      "도형 순서 기억하기",
      "corsi block test",
      "test de memoria secuencial",
      "teste de memoria sequencial",
      "animated",
      "dot",
      "drills",
      "exact",
      "memory",
      "order",
      "path",
      "paths",
      "retrace",
      "spatial",
      "then",
      "tracing",
      "watch"
    ]
  },
  {
    "id": "memory-n-back",
    "name": "3-Back Training",
    "folderName": "n-back",
    "category": "memory",
    "categoryLabel": "Memory Drills",
    "subcategory": "Working Memory",
    "href": "/drills/memory/working-memory/n-back",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Compare current letter with one from 3 steps back",
    "keywords": [
      "3-back",
      "3-back test",
      "back",
      "compare",
      "current",
      "drills",
      "dual n back online",
      "dual n-back",
      "executive function",
      "letter",
      "memory",
      "n-back",
      "n-back online",
      "n-back task",
      "n-back test",
      "steps",
      "training",
      "working",
      "working memory",
      "working memory test"
    ]
  },
  {
    "id": "motor-aim-trainer",
    "name": "Aim Trainer",
    "folderName": "aim-trainer",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/aim-trainer",
    "difficulty": "Hard",
    "duration": "45s+",
    "description": "Dynamic targets that shrink with streak and lives system",
    "keywords": [
      "aim",
      "coordination",
      "dynamic",
      "eye",
      "hand",
      "lives",
      "motor",
      "shrink",
      "skills",
      "streak",
      "system",
      "targets",
      "that",
      "trainer"
    ]
  },
  {
    "id": "motor-drag-and-drop",
    "name": "Drag and Drop Test",
    "folderName": "drag-and-drop",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/drag-and-drop",
    "difficulty": "Easy",
    "duration": "45s",
    "description": "Drag ball into ring within 3s with teleporting positions",
    "keywords": [
      "ball",
      "coordination",
      "drag",
      "drop",
      "eye",
      "hand",
      "into",
      "motor",
      "positions",
      "ring",
      "skills",
      "teleporting",
      "within"
    ]
  },
  {
    "id": "motor-precision-flick-shot",
    "name": "Precision Flick Shot",
    "folderName": "precision-flick-shot",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Hand-Eye Coordination",
    "href": "/drills/motor/hand-eye-coordination/precision-flick-shot",
    "difficulty": "Hard",
    "duration": "45s+",
    "description": "Shrinking aperture flick targets to train visual acquisition and motor centering",
    "keywords": [
      "acquisition",
      "aperture",
      "centering",
      "coordination",
      "eye",
      "flick",
      "hand",
      "motor",
      "precision",
      "shot",
      "shrinking",
      "skills",
      "targets",
      "visual"
    ]
  },
  {
    "id": "motor-finger-sequencing",
    "name": "Sequence Aim Trainer",
    "folderName": "finger-sequencing",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/finger-sequencing",
    "difficulty": "Medium",
    "duration": "45s+",
    "description": "Click 3 nodes from largest to smallest with 2s timer",
    "keywords": [
      "click",
      "finger",
      "from",
      "largest",
      "motor",
      "movement",
      "nodes",
      "sequencing",
      "skills",
      "smallest",
      "speed",
      "timer"
    ]
  },
  {
    "id": "motor-keyboard-recognition",
    "name": "Keyboard Speed Test",
    "folderName": "keyboard-recognition",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/keyboard-recognition",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Professional keyboard speed trainer and custom keybind simulator",
    "keywords": [
      "custom",
      "keybind",
      "keyboard",
      "motor",
      "movement",
      "professional",
      "recognition",
      "simulator",
      "skills",
      "speed",
      "trainer"
    ]
  },
  {
    "id": "motor-rapid-tapping",
    "name": "CPS Test",
    "folderName": "rapid-tapping",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Movement Speed",
    "href": "/drills/motor/movement-speed/rapid-tapping",
    "difficulty": "Easy",
    "duration": "45s",
    "description": "Endless survival clicking with escalating difficulty",
    "keywords": [
      "clicking",
      "difficulty",
      "endless",
      "escalating",
      "motor",
      "movement",
      "rapid",
      "skills",
      "speed",
      "survival",
      "tapping"
    ]
  },
  {
    "id": "motor-steady-hand",
    "name": "Steady Hand Game",
    "folderName": "steady-hand",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Precision Control",
    "href": "/drills/motor/precision-control/steady-hand",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Navigate narrowing wire corridors without touching the boundaries. Measure fine motor steadiness and path control.",
    "keywords": [
      "accot zhai steering law",
      "control",
      "corridor",
      "cursor control",
      "hand",
      "hand steadiness",
      "hand tremor test",
      "motor",
      "mouse control",
      "mouse precision",
      "mouse steadiness",
      "path",
      "precision",
      "steady",
      "steady hand",
      "steady hand game",
      "steady hand test",
      "steady hand tester"
    ]
  },
  {
    "id": "motor-tracing",
    "name": "Mouse Tracing Game",
    "folderName": "tracing",
    "category": "motor",
    "categoryLabel": "Motor Skills",
    "subcategory": "Precision Control",
    "href": "/drills/motor/precision-control/tracing",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Follow a red wave filament with auto-pause and resume",
    "keywords": [
      "auto",
      "control",
      "filament",
      "follow",
      "motor",
      "pause",
      "precision",
      "red",
      "resume",
      "skills",
      "tracing",
      "wave"
    ]
  },
  {
    "id": "physical-stability-challenge",
    "name": "Stability Challenge",
    "folderName": "stability-challenge",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Balance Training",
    "href": "/drills/physical/balance-training/stability-challenge",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Resist wind forces to keep cursor centered with adaptive difficulty",
    "keywords": [
      "adaptive",
      "balance",
      "centered",
      "challenge",
      "cursor",
      "difficulty",
      "drills",
      "forces",
      "keep",
      "physical",
      "resist",
      "stability",
      "training",
      "wind"
    ]
  },
  {
    "id": "physical-complex-pattern",
    "name": "Complex Pattern",
    "folderName": "complex-pattern",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/complex-pattern",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Memorize and draw path patterns from memory with shape-based scoring",
    "keywords": [
      "based",
      "complex",
      "coordination",
      "draw",
      "drills",
      "from",
      "memorize",
      "memory",
      "path",
      "pattern",
      "patterns",
      "physical",
      "scoring",
      "shape"
    ]
  },
  {
    "id": "physical-cross-body-movement",
    "name": "Cross Body Movement",
    "folderName": "cross-body-movement",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/cross-body-movement",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Connect nodes across screen along straight vector paths for +5 points each",
    "keywords": [
      "across",
      "along",
      "body",
      "connect",
      "coordination",
      "cross",
      "drills",
      "each",
      "movement",
      "nodes",
      "paths",
      "physical",
      "points",
      "screen",
      "straight",
      "vector"
    ]
  },
  {
    "id": "physical-dynamic-grid-evasion",
    "name": "Dynamic Grid Evasion",
    "folderName": "dynamic-grid-evasion",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Coordination",
    "href": "/drills/physical/coordination/dynamic-grid-evasion",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Tactical 3x3 grid evasion game to train rapid directional muscle memory",
    "keywords": [
      "3x3",
      "coordination",
      "directional",
      "drills",
      "dynamic",
      "evasion",
      "game",
      "grid",
      "memory",
      "muscle",
      "physical",
      "rapid",
      "tactical"
    ]
  },
  {
    "id": "physical-agility-ladder",
    "name": "Agility Ladder",
    "folderName": "agility-ladder",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/agility-ladder",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Step rungs Left\u2192Right\u2192Left\u2192Right on scrolling ladders with adaptive speed",
    "keywords": [
      "adaptive",
      "agility",
      "drills",
      "fitness",
      "ladder",
      "ladders",
      "left",
      "physical",
      "right",
      "rungs",
      "scrolling",
      "speed",
      "step"
    ]
  },
  {
    "id": "physical-jump-sequence",
    "name": "Jump Sequence",
    "folderName": "jump-sequence",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/jump-sequence",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Charge and launch ball toward targets with mid-air steering control",
    "keywords": [
      "air",
      "ball",
      "charge",
      "control",
      "drills",
      "fitness",
      "jump",
      "launch",
      "mid",
      "physical",
      "sequence",
      "steering",
      "targets",
      "toward"
    ]
  },
  {
    "id": "physical-speed-drill",
    "name": "Speed Drill",
    "folderName": "speed-drill",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Fitness",
    "href": "/drills/physical/fitness/speed-drill",
    "difficulty": "Medium",
    "duration": "45s+",
    "description": "Click shrinking rings before they vanish with velocity scaling to 5.0x",
    "keywords": [
      "before",
      "click",
      "drill",
      "drills",
      "fitness",
      "physical",
      "rings",
      "scaling",
      "shrinking",
      "speed",
      "they",
      "vanish",
      "velocity"
    ]
  },
  {
    "id": "physical-drop-catch",
    "name": "Drop Catch",
    "folderName": "drop-catch",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/drop-catch",
    "difficulty": "Easy",
    "duration": "45s+",
    "description": "Catch green falling balls while avoiding red decoy balls with X markers",
    "keywords": [
      "avoiding",
      "balls",
      "catch",
      "decoy",
      "drills",
      "drop",
      "falling",
      "green",
      "markers",
      "physical",
      "red",
      "reflex",
      "training",
      "while"
    ]
  },
  {
    "id": "physical-peripheral-threat-sweeper",
    "name": "Peripheral Threat Sweeper",
    "folderName": "peripheral-threat-sweeper",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/peripheral-threat-sweeper",
    "difficulty": "Hard",
    "duration": "45s+",
    "description": "Radial perimeter sweeper to train reactive peripheral vision target acquisition",
    "keywords": [
      "acquisition",
      "drills",
      "perimeter",
      "peripheral",
      "physical",
      "radial",
      "reactive",
      "reflex",
      "sweeper",
      "target",
      "threat",
      "training",
      "vision"
    ]
  },
  {
    "id": "physical-quick-dodge",
    "name": "Quick Dodge",
    "folderName": "quick-dodge",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/quick-dodge",
    "difficulty": "Medium",
    "duration": "45s",
    "description": "Dodge red homing obstacles with adaptive speed and fullscreen chaos mode",
    "keywords": [
      "adaptive",
      "chaos",
      "dodge",
      "drills",
      "fullscreen",
      "homing",
      "mode",
      "obstacles",
      "physical",
      "quick",
      "red",
      "reflex",
      "speed",
      "training"
    ]
  },
  {
    "id": "physical-reaction-chain",
    "name": "Reaction Chain",
    "folderName": "reaction-chain",
    "category": "physical",
    "categoryLabel": "Physical Drills",
    "subcategory": "Reflex Training",
    "href": "/drills/physical/reflex-training/reaction-chain",
    "difficulty": "Hard",
    "duration": "45s",
    "description": "Stop cursor on moving nodes to arrest them with no miss penalties",
    "keywords": [
      "arrest",
      "chain",
      "cursor",
      "drills",
      "miss",
      "moving",
      "nodes",
      "penalties",
      "physical",
      "reaction",
      "reflex",
      "stop",
      "them",
      "training"
    ]
  },
  {
    "id": "reaction-speed-barrier-sequence-pursuit",
    "name": "Jiggle Peek Trainer",
    "folderName": "barrier-sequence-pursuit",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/barrier-sequence-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Acquire and click targets flashing behind sequential barrier gates at 4 corners.",
    "keywords": [
      "acquire",
      "barrier",
      "behind",
      "click",
      "corners",
      "flashing",
      "gates",
      "pursuit",
      "reaction",
      "sequence",
      "sequential",
      "speed",
      "targets"
    ]
  },
  {
    "id": "reaction-speed-fps-tracking-trainer",
    "name": "FPS Tracking Trainer",
    "folderName": "fps-tracking-trainer",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/fps-tracking-trainer",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Stabilize gaze and click targets executing erratic, human-like horizontal strafes.",
    "keywords": [
      "click",
      "erratic",
      "executing",
      "fps",
      "gaze",
      "horizontal",
      "human",
      "like",
      "reaction",
      "speed",
      "stabilize",
      "strafes",
      "targets",
      "tracking",
      "trainer"
    ]
  },
  {
    "id": "reaction-speed-market-doors-pursuit",
    "name": "Corner Checking Trainer",
    "folderName": "market-doors-pursuit",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/market-doors-pursuit",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Train horizontal saccadic sweeps by clicking targets that flash behind 5 centered doors.",
    "keywords": [
      "behind",
      "centered",
      "clicking",
      "doors",
      "flash",
      "horizontal",
      "market",
      "pursuit",
      "reaction",
      "saccadic",
      "speed",
      "sweeps",
      "targets",
      "that"
    ]
  },
  {
    "id": "reaction-speed-reaction-game",
    "name": "Reaction Game",
    "folderName": "reaction-game",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reaction-game",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Track and click falling targets along parallel lanes to calibrate vertical reaction limits.",
    "keywords": [
      "along",
      "calibrate",
      "click",
      "falling",
      "game",
      "lanes",
      "limits",
      "parallel",
      "reaction",
      "reflex",
      "saccadic",
      "speed",
      "targets",
      "track",
      "vertical"
    ]
  },
  {
    "id": "reaction-speed-reaction-time-test",
    "name": "Stop the Timer Game",
    "folderName": "reaction-time-test",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reaction-time-test",
    "difficulty": "Beginner",
    "duration": "45s",
    "description": "Memorize a target time, click when it elapses and see your timing error in milliseconds.",
    "keywords": [
      "acquisition",
      "across",
      "calibrate",
      "fast",
      "focus",
      "points",
      "randomly",
      "reaction",
      "snapping",
      "speed",
      "tap",
      "target",
      "test",
      "time",
      "viewport"
    ]
  },
  {
    "id": "reaction-speed-reflex-training-drill",
    "name": "Reflex Training Drill",
    "folderName": "reflex-training-drill",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/reflex-training-drill",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Multiple targets flash on screen at once — clear the whole burst before any of them time out.",
    "keywords": [
      "attention",
      "burst",
      "clear",
      "divided",
      "drill",
      "flash",
      "multiple",
      "reaction",
      "reflex",
      "screen",
      "speed",
      "target",
      "targets",
      "training"
    ]
  },
  {
    "id": "reaction-speed-saccadic-gallery",
    "name": "Saccadic Eye Exercises",
    "folderName": "saccadic-gallery",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/saccadic-gallery",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Sequence-based ballistic eye shifts. Click glowing targets flashing in a zig-zag gallery pattern.",
    "keywords": [
      "ballistic",
      "based",
      "click",
      "eye",
      "flashing",
      "gallery",
      "glowing",
      "pattern",
      "reaction",
      "saccadic",
      "sequence",
      "shifts",
      "speed",
      "targets",
      "zag",
      "zig"
    ]
  },
  {
    "id": "reaction-speed-visual-tracking-speed-test",
    "name": "Visual Tracking Speed Test",
    "folderName": "visual-tracking-speed-test",
    "category": "reaction-speed",
    "categoryLabel": "Reaction Speed",
    "subcategory": "reaction-speed",
    "href": "/drills/reaction-speed/visual-tracking-speed-test",
    "difficulty": "Advanced",
    "duration": "45s+",
    "description": "Click target slides that undergo sudden high-speed burst dash accelerations.",
    "keywords": [
      "accelerations",
      "burst",
      "click",
      "dash",
      "high",
      "reaction",
      "slides",
      "speed",
      "sudden",
      "target",
      "test",
      "that",
      "tracking",
      "undergo",
      "visual"
    ]
  },
  {
    "id": "visual-distance-judgment",
    "name": "Depth Perception Test",
    "folderName": "distance-judgment",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "depth-perception",
    "href": "/drills/visual/depth-perception/distance-judgment",
    "difficulty": "Intermediate",
    "duration": "45s",
    "description": "Intercept approaching 3D targets at the exact target depth plane. Measure looming expansion and distance judgment.",
    "keywords": [
      "close",
      "depth",
      "depth perception",
      "depth perception test",
      "distance",
      "distance judgment",
      "error",
      "intercept",
      "judgment",
      "moving",
      "optical looming",
      "perception",
      "stereoscopic vision",
      "target",
      "time to contact",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-no-go",
    "name": "Chroma-Sync Lab",
    "folderName": "no-go",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "reaction-speed",
    "href": "/drills/visual/reaction-speed/go/no-go",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Click GREEN balls only. Avoid RED balls. Train impulse control and selective response.",
    "keywords": [
      "avoid",
      "balls",
      "chroma",
      "click",
      "control",
      "green",
      "impulse",
      "lab",
      "only",
      "reaction",
      "red",
      "response",
      "selective",
      "speed",
      "sync",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-light-reaction",
    "name": "Strobe-Latency Lab",
    "folderName": "light-reaction",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "reaction-speed",
    "href": "/drills/visual/reaction-speed/light-reaction",
    "difficulty": "Beginner",
    "duration": "45s+",
    "description": "Click when the center ball flashes white. Adaptive 100-200ms window tightens with speed.",
    "keywords": [
      "100",
      "200ms",
      "adaptive",
      "ball",
      "center",
      "click",
      "flashes",
      "lab",
      "latency",
      "light",
      "reaction",
      "speed",
      "strobe",
      "tightens",
      "training",
      "visual",
      "when",
      "white",
      "window"
    ]
  },
  {
    "id": "visual-moving-target",
    "name": "Kinetic Intercept",
    "folderName": "moving-target",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/moving-target",
    "difficulty": "Intermediate",
    "duration": "45s+",
    "description": "Click fast-moving white targets spawning from edges at 12-22 speed.",
    "keywords": [
      "accuracy",
      "click",
      "edges",
      "fast",
      "from",
      "intercept",
      "kinetic",
      "moving",
      "spawning",
      "speed",
      "target",
      "targets",
      "tracking",
      "training",
      "visual",
      "white"
    ]
  },
  {
    "id": "visual-multiple-targets",
    "name": "Ghost-Link Tracking",
    "folderName": "multiple-targets",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/multiple-targets",
    "difficulty": "Expert",
    "duration": "15-60s",
    "description": "Memorize 4 green targets among 11 balls. Track for 60s, then identify them. +5 per correct.",
    "keywords": [
      "60s",
      "accuracy",
      "among",
      "balls",
      "correct",
      "ghost",
      "green",
      "identify",
      "link",
      "memorize",
      "multiple",
      "per",
      "targets",
      "them",
      "then",
      "track",
      "tracking",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-pursuit-tracker",
    "name": "Auto-Pursuit",
    "folderName": "pursuit-tracker",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "tracking-accuracy",
    "href": "/drills/visual/tracking-accuracy/pursuit-tracker",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "Keep cursor on a randomly moving target. +1pt every 0.5s of continuous tracking.",
    "keywords": [
      "1pt",
      "accuracy",
      "auto",
      "continuous",
      "cursor",
      "every",
      "keep",
      "moving",
      "pursuit",
      "randomly",
      "target",
      "tracker",
      "tracking",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-entropic-grid",
    "name": "Entropic Grid",
    "folderName": "entropic-grid",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/entropic-grid",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "Find the 2-char target in a 10x10 grid. Cells randomly corrupt every 800ms. Stamina system with 90s challenge.",
    "keywords": [
      "10x10",
      "800ms",
      "90s",
      "cells",
      "challenge",
      "char",
      "corrupt",
      "entropic",
      "every",
      "find",
      "grid",
      "randomly",
      "recognition",
      "stamina",
      "system",
      "target",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-rhythm-anomaly",
    "name": "Rhythm Anomaly",
    "folderName": "rhythm-anomaly",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/rhythm-anomaly",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "Find the faster-pulsing cell (1.4s) among steady cells (2s) in a 6x6 grid. Stamina system.",
    "keywords": [
      "6x6",
      "among",
      "anomaly",
      "cell",
      "cells",
      "faster",
      "find",
      "grid",
      "pulsing",
      "recognition",
      "rhythm",
      "stamina",
      "steady",
      "system",
      "training",
      "visual"
    ]
  },
  {
    "id": "visual-visual-search",
    "name": "Visual Search",
    "folderName": "visual-search",
    "category": "visual",
    "categoryLabel": "Visual Training",
    "subcategory": "visual-recognition",
    "href": "/drills/visual/visual-recognition/visual-search",
    "difficulty": "Advanced",
    "duration": "45s",
    "description": "Find the letter C among 160 O distractors in a 16x10 grid. +1 per find, -1 wrong.",
    "keywords": [
      "160",
      "16x10",
      "among",
      "distractors",
      "find",
      "grid",
      "letter",
      "per",
      "recognition",
      "search",
      "training",
      "visual",
      "wrong"
    ]
  },
  {
    "id": "visual-tracking-constant-slow-pursuit",
    "name": "Constant Slow Pursuit",
    "folderName": "constant-slow-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/constant-slow-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s",
    "description": "Condition foveal pursuit along a continuous, visible Lissajous curve at low velocity.",
    "keywords": [
      "along",
      "condition",
      "constant",
      "continuous",
      "curve",
      "foveal",
      "lissajous",
      "low",
      "pursuit",
      "slow",
      "tracking",
      "velocity",
      "visible",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-directional-chaos-pursuit",
    "name": "Directional Chaos Pursuit",
    "folderName": "directional-chaos-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/directional-chaos-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s",
    "description": "Track a bouncing target subjected to continuous chaotic velocity nudges.",
    "keywords": [
      "bouncing",
      "chaos",
      "chaotic",
      "continuous",
      "directional",
      "nudges",
      "pursuit",
      "subjected",
      "target",
      "track",
      "tracking",
      "velocity",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-dynamic-evasion-pursuit",
    "name": "Dynamic Evasion Pursuit",
    "folderName": "dynamic-evasion-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/dynamic-evasion-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s",
    "description": "Overclock tracking responses against rapid directional changes at constant speed scales.",
    "keywords": [
      "against",
      "changes",
      "constant",
      "directional",
      "dynamic",
      "evasion",
      "overclock",
      "pursuit",
      "rapid",
      "responses",
      "scales",
      "speed",
      "tracking",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-ghosting-suppress-pursuit",
    "name": "Ghosting Suppress Pursuit",
    "folderName": "ghosting-suppress-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/ghosting-suppress-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s",
    "description": "Suppress lag indicators and trail overlays to isolate target tracking.",
    "keywords": [
      "ghosting",
      "indicators",
      "isolate",
      "lag",
      "overlays",
      "pursuit",
      "suppress",
      "target",
      "tracking",
      "trail",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-infinity-pursuit",
    "name": "Infinity Pursuit",
    "folderName": "infinity-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/infinity-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s",
    "description": "Track a target moving along a visible figure-8 Lemniscate path at a fluid pace.",
    "keywords": [
      "along",
      "figure",
      "fluid",
      "infinity",
      "lemniscate",
      "moving",
      "pace",
      "path",
      "pursuit",
      "target",
      "track",
      "tracking",
      "visible",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-momentum-teleport-pursuit",
    "name": "Momentum Teleport Pursuit",
    "folderName": "momentum-teleport-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/momentum-teleport-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s",
    "description": "Predict target direction after coordinates instantly teleport while maintaining velocity momentum.",
    "keywords": [
      "after",
      "coordinates",
      "direction",
      "instantly",
      "maintaining",
      "momentum",
      "predict",
      "pursuit",
      "target",
      "teleport",
      "tracking",
      "velocity",
      "visual",
      "while"
    ]
  },
  {
    "id": "visual-tracking-peripheral-ping-pursuit",
    "name": "Peripheral Ping Pursuit",
    "folderName": "peripheral-ping-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/peripheral-ping-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s",
    "description": "Fixate on center crosshairs while detecting transient targets spawning in your peripheral view.",
    "keywords": [
      "center",
      "crosshairs",
      "detecting",
      "fixate",
      "peripheral",
      "ping",
      "pursuit",
      "spawning",
      "targets",
      "tracking",
      "transient",
      "view",
      "visual",
      "while"
    ]
  },
  {
    "id": "visual-tracking-predictive-pursuit",
    "name": "Predictive Pursuit",
    "folderName": "predictive-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/predictive-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s",
    "description": "Interpolate path trajectory of a moving cyan shadow and execute ballistic gaze shifts to capture solidified targets.",
    "keywords": [
      "ballistic",
      "capture",
      "cyan",
      "execute",
      "gaze",
      "interpolate",
      "moving",
      "path",
      "predictive",
      "pursuit",
      "shadow",
      "shifts",
      "solidified",
      "targets",
      "tracking",
      "trajectory",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-sine-wave-pursuit",
    "name": "Sine-Wave Pursuit",
    "folderName": "sine-wave-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/sine-wave-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s",
    "description": "Track target oscillations along a horizontal sine wave guide line.",
    "keywords": [
      "along",
      "guide",
      "horizontal",
      "line",
      "oscillations",
      "pursuit",
      "sine",
      "target",
      "track",
      "tracking",
      "visual",
      "wave"
    ]
  },
  {
    "id": "visual-tracking-spatial-shift-pursuit",
    "name": "Spatial-Shift Pursuit",
    "folderName": "spatial-shift-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/spatial-shift-pursuit",
    "difficulty": "Intermediate",
    "duration": "30-120s",
    "description": "Track a bouncing target that undergoes randomized shifts in speed and direction.",
    "keywords": [
      "bouncing",
      "direction",
      "pursuit",
      "randomized",
      "shift",
      "shifts",
      "spatial",
      "speed",
      "target",
      "that",
      "track",
      "tracking",
      "undergoes",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-split-screen-tracking",
    "name": "Split-Screen Tracking",
    "folderName": "split-screen-tracking",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/split-screen-tracking",
    "difficulty": "Intermediate",
    "duration": "30-120s",
    "description": "Condition divided attention by tracking two targets moving along vertical and horizontal planes.",
    "keywords": [
      "along",
      "attention",
      "condition",
      "divided",
      "horizontal",
      "moving",
      "planes",
      "screen",
      "split",
      "targets",
      "tracking",
      "two",
      "vertical",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-staircase-step",
    "name": "Vertical Tracking",
    "folderName": "staircase-step",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/staircase-step",
    "difficulty": "Intermediate",
    "duration": "30-120s",
    "description": "Track stepped trajectories combining horizontal slides with rapid vertical snaps.",
    "keywords": [
      "combining",
      "horizontal",
      "rapid",
      "slides",
      "snaps",
      "staircase",
      "step",
      "stepped",
      "track",
      "tracking",
      "trajectories",
      "vertical",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-strobe-prediction-pursuit",
    "name": "Occlusion Prediction Pursuit",
    "folderName": "strobe-prediction-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/strobe-prediction-pursuit",
    "difficulty": "Advanced",
    "duration": "30-120s",
    "description": "Estimate a moving target's reappearance during controlled occlusion; browser practice, not a clinical measure.",
    "keywords": [
      "blank",
      "cyclic",
      "during",
      "intervals",
      "locations",
      "memory",
      "predict",
      "prediction",
      "pursuit",
      "occlusion",
      "target",
      "tracking",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-triangular-pursuit",
    "name": "Triangular Pursuit",
    "folderName": "triangular-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/triangular-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s",
    "description": "Track target transitions along a visible triangular guide vector.",
    "keywords": [
      "along",
      "guide",
      "pursuit",
      "target",
      "track",
      "tracking",
      "transitions",
      "triangular",
      "vector",
      "visible",
      "visual"
    ]
  },
  {
    "id": "visual-tracking-zig-zag-path-pursuit",
    "name": "Zig-Zag Path Pursuit",
    "folderName": "zig-zag-path-pursuit",
    "category": "visual-tracking",
    "categoryLabel": "Visual Tracking",
    "subcategory": "visual-tracking",
    "href": "/drills/visual-tracking/zig-zag-path-pursuit",
    "difficulty": "Beginner",
    "duration": "30-120s",
    "description": "Track target movements along a visible multi-segment zig-zag guide path.",
    "keywords": [
      "along",
      "guide",
      "movements",
      "multi",
      "path",
      "pursuit",
      "segment",
      "target",
      "track",
      "tracking",
      "visible",
      "visual",
      "zag",
      "zig"
    ]
  }
];
