const FAQS = {
  en: [
    ["What is memory training?", "Memory training uses repeatable recall tasks to practise holding, updating, and retrieving information. SkillDrills separates number, word, colour, pattern, and spatial tasks so you can choose a clear starting point."],
    ["What is the difference between short-term and working memory?", "Short-term memory briefly holds information. Working memory also updates or manipulates it, such as reversing digits, matching a sequence, or following a changing rule. The two systems overlap but are not identical."],
    ["Which memory drill should I start with?", "Start with Digit Span for a simple number-recall baseline, Word Recall for verbal memory, Color Sequence for visual order, N-Back for updating, or Grid Memorization for visuospatial recall."],
    ["Can memory games improve everyday memory?", "They give you structured practice with specific recall processes. Improvement is usually strongest on similar tasks, while transfer to study, work, or daily life varies with sleep, attention, strategy, and continued practice."],
    ["What is a good digit-span score?", "A browser score is a personal practice measure, not a diagnosis or universal norm. Compare repeated attempts under the same screen, input, and distraction conditions instead of treating one number as a fixed ability label."],
    ["How does chunking help memory?", "Chunking groups separate items into meaningful units, such as reading 14922026 as three familiar groups. It reduces the number of units you must actively track, but it does not remove the need for attention and accurate recall."],
    ["How often should I practise memory drills?", "Use short, focused sessions and stop when accuracy or attention drops. A consistent 5–15 minute routine several times a week is easier to compare than infrequent sessions performed while tired."],
    ["Do spatial memory drills train the same skill as word recall?", "No. Word recall emphasizes verbal encoding and retrieval, while grid and path tasks emphasize visual-spatial locations and order. Rotating both types gives a broader practice profile."],
    ["Are browser memory drills medical or IQ tests?", "No. They are interactive practice and self-tracking tools. A browser result is affected by device, attention, familiarity, and task design and should not be used to diagnose a condition or estimate intelligence."],
    ["How can I make my memory-training results more reliable?", "Keep the device, browser, volume, screen distance, and session length similar. Avoid multitasking, record several rounds, and compare your median or typical result rather than your single best attempt."]
  ],
  ko: [
    ["기억력 훈련이란 무엇인가요?", "기억력 훈련은 정보를 잠시 유지하고, 갱신하고, 다시 떠올리는 과제를 반복하는 연습입니다. 숫자·단어·색 순서·패턴·공간 과제를 나누어 목적에 맞는 시작점을 고를 수 있습니다."],
    ["단기기억과 작업기억은 어떻게 다른가요?", "단기기억은 정보를 짧게 보관하는 기능입니다. 작업기억은 숫자를 거꾸로 말하거나 바뀌는 규칙을 따라가는 것처럼 정보를 유지하면서 동시에 조작하고 갱신합니다."],
    ["어떤 기억력 드릴부터 시작하면 좋나요?", "숫자 회상 기준을 보려면 숫자 기억, 언어 기억은 단어 회상, 시각적 순서는 색 순서, 갱신 능력은 N-back, 시공간 기억은 격자 기억부터 시작하세요."],
    ["기억력 게임이 일상 기억력 향상에 도움이 되나요?", "특정 회상 과정을 구조적으로 연습할 수 있습니다. 효과는 비슷한 과제에서 가장 뚜렷하고, 공부나 업무로의 전이는 수면·집중·전략·꾸준함에 따라 달라집니다."],
    ["숫자 기억 점수는 어느 정도가 좋은가요?", "브라우저 점수는 진단이나 절대적인 기준이 아니라 개인 연습 기록입니다. 한 번의 최고 점수보다 같은 화면과 입력 조건에서 반복한 결과를 비교하세요."],
    ["청킹은 기억에 어떻게 도움이 되나요?", "청킹은 여러 항목을 의미 있는 묶음으로 정리하는 방법입니다. 예를 들어 숫자를 익숙한 세 묶음으로 나누면 동시에 추적할 단위가 줄어들지만 집중과 정확한 회상은 여전히 필요합니다."],
    ["기억력 드릴은 얼마나 자주 해야 하나요?", "집중이 유지되는 짧은 세션을 사용하고 정확도가 떨어지면 쉬세요. 일주일에 여러 번 5~15분씩 꾸준히 하는 편이 지친 상태의 긴 세션보다 비교하기 쉽습니다."],
    ["공간 기억과 단어 회상은 같은 능력인가요?", "아닙니다. 단어 회상은 언어적 부호화와 인출을, 격자와 경로 과제는 위치와 순서를 기억하는 시공간 처리를 주로 사용합니다. 두 유형을 번갈아 연습하면 범위를 넓힐 수 있습니다."],
    ["브라우저 기억력 드릴은 의학 검사나 IQ 검사인가요?", "아닙니다. 인터랙티브 연습과 개인 기록 도구입니다. 기기, 집중도, 익숙함, 과제 설계가 결과에 영향을 주므로 질환 진단이나 지능 추정에 사용하면 안 됩니다."],
    ["기억력 훈련 결과를 더 일정하게 비교하려면 어떻게 하나요?", "기기·브라우저·볼륨·화면 거리·세션 길이를 비슷하게 유지하세요. 멀티태스킹을 피하고 여러 라운드를 기록한 뒤 한 번의 최고 기록보다 보통 수준이나 중앙값을 비교하세요."]
  ],
  ja: [
    ["記憶力トレーニングとは何ですか？", "記憶力トレーニングは、情報を一時的に保ち、更新し、思い出す課題を繰り返す練習です。数字、単語、色の順序、パターン、空間課題から目的に合うものを選べます。"],
    ["短期記憶とワーキングメモリはどう違いますか？", "短期記憶は情報を短時間保つ機能です。ワーキングメモリは数字を逆順にしたり、変化するルールに従ったりしながら、情報を保持して操作・更新します。"],
    ["どの記憶力ドリルから始めればよいですか？", "数字の基準には数字記憶、言語的な想起には単語記憶、視覚的な順序には色の順序、更新にはNバック、視空間記憶にはグリッド記憶から始めてください。"],
    ["記憶力ゲームは日常の記憶に役立ちますか？", "特定の想起処理を構造化して練習できます。上達は似た課題で最も現れやすく、勉強や仕事への転移は睡眠、注意、方略、継続によって変わります。"],
    ["数字記憶のスコアはどのくらいなら良いですか？", "ブラウザのスコアは診断や共通の基準ではなく、個人の練習記録です。一度の最高値ではなく、同じ画面と入力条件で繰り返した結果を比べてください。"],
    ["チャンク化は記憶にどう役立ちますか？", "チャンク化は複数の項目を意味のあるまとまりに整理する方法です。数字を覚えやすい組に分けると追跡する単位が減りますが、注意と正確な想起は必要です。"],
    ["記憶力ドリルはどのくらいの頻度で行えばよいですか？", "集中できる短いセッションを使い、正確さが落ちたら休んでください。週に数回、5〜15分ほど続けるほうが、疲れた状態の長時間練習より比べやすくなります。"],
    ["空間記憶と単語記憶は同じ能力ですか？", "同じではありません。単語記憶は言語的な符号化と想起、グリッドや経路は位置と順序を覚える視空間処理を主に使います。両方を交互に練習すると幅が広がります。"],
    ["ブラウザの記憶力ドリルは医学検査やIQテストですか？", "いいえ。インタラクティブな練習と記録のためのツールです。機器、集中、慣れ、課題設計が結果に影響するため、診断や知能の推定には使えません。"],
    ["記憶力トレーニングの結果を安定して比べるには？", "機器、ブラウザ、音量、画面との距離、セッション時間をそろえます。ながら作業を避け、複数ラウンドを記録し、一番良い値より典型的な値や中央値を比べてください。"]
  ],
  de: [
    ["Was ist Gedächtnistraining?", "Gedächtnistraining nutzt wiederholbare Aufgaben zum Behalten, Aktualisieren und Abrufen von Informationen. Bei SkillDrills kannst du Zahlen, Wörter, Farben, Muster und räumliche Aufgaben getrennt üben."],
    ["Was ist der Unterschied zwischen Kurzzeitgedächtnis und Arbeitsgedächtnis?", "Das Kurzzeitgedächtnis hält Informationen kurz bereit. Das Arbeitsgedächtnis verarbeitet sie zusätzlich, etwa wenn du Zahlen umkehrst oder einer wechselnden Regel folgst."],
    ["Mit welcher Gedächtnisübung sollte ich beginnen?", "Beginne mit Zahlenspanne für eine einfache Zahlenbasis, Wortabruf für verbales Erinnern, Farbfolge für visuelle Reihenfolgen, N-Back für Aktualisieren oder Gitter-Merken für räumliche Erinnerung."],
    ["Können Gedächtnisspiele das Gedächtnis im Alltag verbessern?", "Sie üben bestimmte Abrufprozesse strukturiert. Fortschritte sind meist bei ähnlichen Aufgaben am deutlichsten; der Transfer auf Lernen, Arbeit oder Alltag hängt auch von Schlaf, Aufmerksamkeit und Übung ab."],
    ["Welche Zahlenspanne ist gut?", "Ein Browserwert ist eine persönliche Trainingsgröße und keine Diagnose oder allgemeingültige Norm. Vergleiche mehrere Versuche unter denselben Bedingungen statt nur den besten Einzelwert."],
    ["Wie hilft Chunking beim Merken?", "Chunking fasst einzelne Elemente zu sinnvollen Einheiten zusammen, zum Beispiel Ziffern in vertraute Gruppen. Dadurch sinkt die Zahl der aktiv verfolgten Einheiten, Aufmerksamkeit bleibt aber erforderlich."],
    ["Wie oft sollte ich Gedächtnisübungen machen?", "Nutze kurze, konzentrierte Einheiten und pausiere bei nachlassender Genauigkeit. Mehrmals pro Woche 5 bis 15 Minuten sind leichter vergleichbar als seltene, ermüdende lange Sitzungen."],
    ["Trainiert räumliches Gedächtnis dasselbe wie Wortabruf?", "Nein. Wortabruf beansprucht vor allem sprachliche Enkodierung und Abruf, während Gitter- und Pfadaufgaben Positionen und Reihenfolgen visuell-räumlich verarbeiten. Beide Bereiche ergänzen sich."],
    ["Sind Browser-Gedächtnisübungen medizinische oder IQ-Tests?", "Nein. Sie dienen dem Üben und der persönlichen Verlaufskontrolle. Gerät, Aufmerksamkeit, Vertrautheit und Aufgabendesign beeinflussen das Ergebnis; es ist keine Diagnose und keine IQ-Schätzung."],
    ["Wie werden Ergebnisse beim Gedächtnistraining vergleichbarer?", "Halte Gerät, Browser, Lautstärke, Abstand zum Bildschirm und Sitzungsdauer ähnlich. Vermeide Multitasking und vergleiche den typischen oder mittleren Wert mehrerer Runden."]
  ],
  pt: [
    ["O que é treino de memória?", "Treino de memória usa tarefas repetíveis para manter, atualizar e recuperar informações. No SkillDrills, você pode praticar números, palavras, cores, padrões e posições espaciais separadamente."],
    ["Qual é a diferença entre memória de curto prazo e memória de trabalho?", "A memória de curto prazo mantém informações por pouco tempo. A memória de trabalho também as manipula e atualiza, como ao inverter números ou acompanhar uma regra que muda."],
    ["Por qual exercício de memória devo começar?", "Comece por Span de Dígitos para uma referência numérica, Recordação de Palavras para memória verbal, Sequência de Cores para ordem visual, N-Back para atualização ou Memorização de Grade para memória espacial."],
    ["Jogos de memória ajudam na memória do dia a dia?", "Eles oferecem prática estruturada de processos específicos de recordação. O ganho costuma ser maior em tarefas parecidas; a transferência para estudo, trabalho ou rotina varia com sono, atenção, estratégia e constância."],
    ["Qual é uma boa pontuação no span de dígitos?", "A pontuação no navegador é uma medida pessoal de treino, não um diagnóstico nem uma norma universal. Compare várias tentativas nas mesmas condições em vez de usar apenas o melhor resultado."],
    ["Como o agrupamento ajuda a memória?", "Agrupamento organiza itens separados em unidades com significado, como dividir algarismos em grupos conhecidos. Isso reduz as unidades acompanhadas ao mesmo tempo, mas ainda exige atenção e recordação precisa."],
    ["Com que frequência devo treinar a memória?", "Faça sessões curtas e concentradas, parando quando a precisão cair. Praticar 5 a 15 minutos algumas vezes por semana é mais comparável do que sessões longas e cansativas de vez em quando."],
    ["Memória espacial e recordação de palavras são a mesma habilidade?", "Não. Palavras dependem mais de codificação e recuperação verbal; grades e caminhos dependem de posições e ordem visuoespaciais. Alternar os dois tipos amplia o perfil de treino."],
    ["Os exercícios de memória no navegador são testes médicos ou de QI?", "Não. São ferramentas interativas de prática e acompanhamento pessoal. Dispositivo, atenção, familiaridade e desenho da tarefa afetam o resultado; ele não diagnostica nem estima inteligência."],
    ["Como comparar melhor meus resultados de treino?", "Mantenha dispositivo, navegador, volume, distância da tela e duração parecidos. Evite fazer várias tarefas ao mesmo tempo, registre várias rodadas e compare o resultado típico ou mediano."]
  ],
  es: [
    ["¿Qué es el entrenamiento de memoria?", "El entrenamiento de memoria usa tareas repetibles para mantener, actualizar y recuperar información. En SkillDrills puedes practicar números, palabras, colores, patrones y posiciones espaciales por separado."],
    ["¿Qué diferencia hay entre memoria a corto plazo y memoria de trabajo?", "La memoria a corto plazo mantiene información durante poco tiempo. La memoria de trabajo también la manipula y actualiza, por ejemplo al invertir números o seguir una regla cambiante."],
    ["¿Con qué ejercicio de memoria debería empezar?", "Empieza con Span de Dígitos para una referencia numérica, Recuerdo de Palabras para memoria verbal, Secuencia de Colores para orden visual, N-Back para actualización o Memorización de Cuadrícula para memoria espacial."],
    ["¿Los juegos de memoria ayudan a la memoria cotidiana?", "Ofrecen práctica estructurada de procesos concretos de recuerdo. La mejora suele ser mayor en tareas parecidas; la transferencia al estudio, trabajo o vida diaria depende también del sueño, la atención y la constancia."],
    ["¿Qué puntuación es buena en el span de dígitos?", "La puntuación del navegador es una medida personal de práctica, no un diagnóstico ni una norma universal. Compara varios intentos en las mismas condiciones y no solo tu mejor resultado."],
    ["¿Cómo ayuda agrupar la información a recordar?", "Agrupar reúne elementos separados en unidades con significado, como dividir cifras en grupos conocidos. Reduce las unidades que sigues a la vez, pero aún requiere atención y recuerdo preciso."],
    ["¿Con qué frecuencia debo practicar la memoria?", "Haz sesiones breves y concentradas y descansa cuando baje la precisión. Practicar de 5 a 15 minutos varias veces por semana es más fácil de comparar que sesiones largas y agotadoras poco frecuentes."],
    ["¿La memoria espacial es igual que recordar palabras?", "No. Recordar palabras depende más de la codificación y recuperación verbal; las cuadrículas y rutas trabajan posiciones y orden visuoespaciales. Alternar ambos tipos amplía la práctica."],
    ["¿Los ejercicios de memoria del navegador son pruebas médicas o de CI?", "No. Son herramientas interactivas de práctica y seguimiento personal. El dispositivo, la atención, la familiaridad y el diseño de la tarea influyen en el resultado; no diagnostica ni estima la inteligencia."],
    ["¿Cómo puedo comparar mejor mis resultados?", "Mantén parecidos el dispositivo, navegador, volumen, distancia a la pantalla y duración. Evita la multitarea, registra varias rondas y compara el resultado habitual o mediano."]
  ],
  fr: [
    ["Qu'est-ce que l'entraînement de la mémoire ?", "L'entraînement de la mémoire utilise des tâches répétables pour retenir, mettre à jour et retrouver des informations. SkillDrills sépare les nombres, mots, couleurs, motifs et positions spatiales."],
    ["Quelle différence entre mémoire à court terme et mémoire de travail ?", "La mémoire à court terme garde une information brièvement. La mémoire de travail la manipule et la met aussi à jour, par exemple pour inverser des chiffres ou suivre une règle qui change."],
    ["Quel exercice de mémoire choisir pour commencer ?", "Commencez par l'empan de chiffres pour une base numérique, le rappel de mots pour la mémoire verbale, la séquence de couleurs pour l'ordre visuel, N-Back pour la mise à jour ou la grille pour la mémoire spatiale."],
    ["Les jeux de mémoire aident-ils la mémoire au quotidien ?", "Ils permettent de pratiquer des processus de rappel précis. Les progrès sont généralement les plus nets sur des tâches proches; le transfert vers les études, le travail ou la vie courante varie selon le sommeil, l'attention et la régularité."],
    ["Quel est un bon score à l'empan de chiffres ?", "Un score dans le navigateur est une mesure personnelle d'entraînement, pas un diagnostic ni une norme universelle. Comparez plusieurs essais dans les mêmes conditions plutôt que votre meilleur essai isolé."],
    ["Comment le regroupement aide-t-il la mémoire ?", "Le regroupement rassemble des éléments séparés en unités porteuses de sens, par exemple des chiffres en groupes familiers. Il réduit le nombre d'unités suivies, sans supprimer le besoin d'attention."],
    ["À quelle fréquence pratiquer les exercices de mémoire ?", "Faites des séances courtes et concentrées et arrêtez-vous quand la précision baisse. Cinq à quinze minutes plusieurs fois par semaine sont plus comparables que de longues séances fatigantes et rares."],
    ["La mémoire spatiale est-elle la même que le rappel de mots ?", "Non. Le rappel de mots sollicite surtout l'encodage et la récupération verbale; les grilles et les chemins sollicitent les positions et l'ordre visuo-spatiaux. Alterner les deux élargit l'entraînement."],
    ["Les exercices de mémoire en ligne sont-ils des tests médicaux ou de QI ?", "Non. Ce sont des outils interactifs d'exercice et de suivi personnel. L'appareil, l'attention, l'habitude et la conception de la tâche influencent le résultat; il ne diagnostique rien et n'estime pas le QI."],
    ["Comment rendre mes résultats plus comparables ?", "Gardez le même appareil, navigateur, volume, distance à l'écran et durée de session. Évitez le multitâche, notez plusieurs manches et comparez le résultat habituel ou médian."]
  ]
};

const UI = {
  en: { locale: "en_US", language: "en-US", title: "Memory Tests & Memory Games", description: "Free memory tests and memory games for short-term, working, and spatial memory. Try digit span, pattern recall, and route memory in your browser.", keywords: ["memory test", "memory training", "working memory", "short term memory", "spatial memory", "digit span", "visual memory test", "memory drills online"], h1: "Memory Tests & Memory Games", intro: "Choose a focused browser drill for number recall, word memory, visual sequences, working-memory updates, or spatial routes. Compare repeatable sessions under the same device conditions.", drillsHeading: "Memory drills", viewAll: "View all", domainsTitle: "Memory training domains", drill: "Drill", drills: "Drills", hardwareTitle: "Browser, display & input conditions", hardware: [{ title: "Stimulus timing", description: "Local tasks use high-resolution performance clocks, but frame timing and browser scheduling can still affect a recall result." }, { title: "Adaptive load", description: "Progressive levels make it easier to compare practice within one task; they do not create a clinical cognitive score." }, { title: "Local progress", description: "Your streaks and practice history stay in the browser so the page can respond without account or network delay." }], faqTitle: "Memory training questions", returnAll: "Return to all drill categories", startDrill: "Start Memory Drill", breadcrumbHome: "Home", breadcrumbDrills: "Drills", breadcrumbCurrent: "Memory training" },
  ko: { locale: "ko_KR", language: "ko-KR", title: "기억력 테스트와 기억력 훈련", description: "단기기억, 작업기억, 공간기억을 연습하는 무료 기억력 테스트입니다. 숫자·패턴·경로 회상을 브라우저에서 바로 훈련하세요.", keywords: ["기억력 테스트", "기억력 훈련", "작업기억", "단기기억", "공간기억", "숫자 기억", "시각 기억력 테스트", "기억력 게임"], h1: "기억력 테스트와 기억력 훈련", intro: "숫자 회상, 단어 기억, 시각 순서, 작업기억 갱신, 공간 경로 중 원하는 브라우저 드릴을 선택하세요. 같은 기기 조건에서 반복 세션을 비교할 수 있습니다.", drillsHeading: "기억력 훈련 드릴", viewAll: "전체 보기", domainsTitle: "기억력 훈련 분야", drill: "드릴", drills: "드릴", hardwareTitle: "브라우저·화면·입력 조건", hardware: [{ title: "자극 표시 시간", description: "로컬 과제는 고해상도 성능 시계를 사용하지만 프레임 시점과 브라우저 처리도 회상 결과에 영향을 줄 수 있습니다." }, { title: "난이도 조절", description: "단계별 난이도는 하나의 과제 안에서 연습을 비교하기 쉽게 하지만 임상 인지 점수를 만들지는 않습니다." }, { title: "브라우저 내 기록", description: "연속 기록과 연습 이력은 브라우저에 보관되므로 계정이나 네트워크 지연 없이 진행 상황을 확인할 수 있습니다." }], faqTitle: "기억력 훈련 자주 묻는 질문", returnAll: "전체 드릴 카테고리로 돌아가기", startDrill: "기억력 드릴 시작", breadcrumbHome: "홈", breadcrumbDrills: "드릴", breadcrumbCurrent: "기억력 훈련" },
  ja: { locale: "ja_JP", language: "ja-JP", title: "記憶力テストと記憶力トレーニング", description: "短期記憶、ワーキングメモリ、空間記憶を練習できる無料の記憶力テスト。数字・パターン・経路の想起をブラウザで行えます。", keywords: ["記憶力 テスト", "記憶力 トレーニング", "ワーキングメモリ", "短期記憶", "空間記憶", "数字記憶", "視覚記憶 テスト", "記憶力 ゲーム"], h1: "記憶力テストと記憶力トレーニング", intro: "数字、単語、視覚的な順序、ワーキングメモリの更新、空間経路から目的に合うブラウザ練習を選べます。同じ機器条件で繰り返し比べてください。", drillsHeading: "記憶力ドリル", viewAll: "すべて見る", domainsTitle: "記憶力トレーニングの分野", drill: "ドリル", drills: "ドリル", hardwareTitle: "ブラウザ・画面・入力条件", hardware: [{ title: "刺激の表示時間", description: "ローカル課題は高精度の時計を使いますが、フレームのタイミングとブラウザ処理も想起結果に影響します。" }, { title: "負荷の調整", description: "段階的なレベルは同じ課題の練習を比べやすくしますが、臨床的な認知スコアにはなりません。" }, { title: "ブラウザ内の記録", description: "連続記録と練習履歴はブラウザに保存され、アカウントや通信遅延なしで進み具合を確認できます。" }], faqTitle: "記憶力トレーニングのよくある質問", returnAll: "すべてのドリルカテゴリへ戻る", startDrill: "記憶力ドリルを始める", breadcrumbHome: "ホーム", breadcrumbDrills: "ドリル", breadcrumbCurrent: "記憶力トレーニング" },
  de: { locale: "de_DE", language: "de-DE", title: "Gedächtnistest & Gedächtnistraining kostenlos", description: "Kostenlose Gedächtnistests für Kurzzeit-, Arbeits- und räumliches Gedächtnis. Übe Zahlenspanne, Musterabruf und Weggedächtnis direkt im Browser.", keywords: ["Gedächtnistest", "Gedächtnistraining", "Arbeitsgedächtnis", "Kurzzeitgedächtnis", "räumliches Gedächtnis", "Zahlenspanne", "visueller Gedächtnistest", "Gedächtnisübungen online"], h1: "Gedächtnistest & Gedächtnistraining", intro: "Wähle eine Browserübung für Zahlen, Wörter, visuelle Reihenfolgen, Arbeitsgedächtnis oder räumliche Wege. Vergleiche wiederholbare Sitzungen unter denselben Gerätebedingungen.", drillsHeading: "Gedächtnisübungen", viewAll: "Alle anzeigen", domainsTitle: "Bereiche des Gedächtnistrainings", drill: "Übung", drills: "Übungen", hardwareTitle: "Browser-, Display- und Eingabebedingungen", hardware: [{ title: "Reizzeitpunkt", description: "Lokale Aufgaben verwenden hochauflösende Performance-Uhren, aber Frame-Zeitpunkt und Browserplanung können das Ergebnis beeinflussen." }, { title: "Adaptive Belastung", description: "Stufenweise Aufgaben erleichtern den Vergleich innerhalb einer Übung, ergeben aber keinen klinischen Kognitionswert." }, { title: "Lokaler Fortschritt", description: "Serien und Übungsverlauf bleiben im Browser, damit der Fortschritt ohne Konto oder Netzwerklatenz angezeigt wird." }], faqTitle: "Fragen zum Gedächtnistraining", returnAll: "Zu allen Drill-Kategorien", startDrill: "Gedächtnisübung starten", breadcrumbHome: "Startseite", breadcrumbDrills: "Drills", breadcrumbCurrent: "Gedächtnistraining" },
  pt: { locale: "pt_BR", language: "pt-BR", title: "Testes de Memória e Treino de Memória", description: "Testes gratuitos de memória de curto prazo, memória de trabalho e memória espacial. Pratique números, padrões e caminhos direto no navegador.", keywords: ["teste de memória", "treino de memória", "memória de trabalho", "memória de curto prazo", "memória espacial", "span de dígitos", "teste de memória visual", "jogos de memória online"], h1: "Testes de Memória e Treino de Memória", intro: "Escolha um treino no navegador para recordar números, palavras, sequências visuais, atualizar a memória de trabalho ou seguir caminhos espaciais. Compare sessões nas mesmas condições.", drillsHeading: "Treinos de memória", viewAll: "Ver todos", domainsTitle: "Áreas do treino de memória", drill: "Treino", drills: "Treinos", hardwareTitle: "Condições do navegador, tela e entrada", hardware: [{ title: "Tempo do estímulo", description: "As tarefas locais usam relógios de alta resolução, mas o quadro exibido e o agendamento do navegador podem afetar o resultado." }, { title: "Carga adaptativa", description: "Níveis progressivos facilitam comparar a prática dentro de uma tarefa, mas não produzem uma pontuação cognitiva clínica." }, { title: "Progresso local", description: "Sequências e histórico ficam no navegador para mostrar seu progresso sem conta ou atraso de rede." }], faqTitle: "Dúvidas sobre treino de memória", returnAll: "Voltar a todas as categorias", startDrill: "Começar treino de memória", breadcrumbHome: "Início", breadcrumbDrills: "Treinos", breadcrumbCurrent: "Treino de memória" },
  es: { locale: "es_ES", language: "es-ES", title: "Test de Memoria Online y Entrenamiento", description: "Tests gratuitos de memoria a corto plazo, de trabajo y espacial. Practica números, patrones y rutas directamente en el navegador.", keywords: ["test de memoria", "entrenamiento de memoria", "memoria de trabajo", "memoria a corto plazo", "memoria espacial", "span de dígitos", "test de memoria visual", "juegos de memoria online"], h1: "Test de Memoria Online y Entrenamiento", intro: "Elige un ejercicio de navegador para recordar números, palabras, secuencias visuales, actualizar la memoria de trabajo o seguir rutas espaciales. Compara sesiones con el mismo dispositivo.", drillsHeading: "Ejercicios de memoria", viewAll: "Ver todos", domainsTitle: "Áreas del entrenamiento de memoria", drill: "Ejercicio", drills: "Ejercicios", hardwareTitle: "Condiciones del navegador, pantalla y entrada", hardware: [{ title: "Momento del estímulo", description: "Las tareas locales usan relojes de alta resolución, pero el fotograma mostrado y la planificación del navegador pueden afectar al resultado." }, { title: "Carga adaptativa", description: "Los niveles progresivos facilitan comparar la práctica dentro de una tarea, pero no crean una puntuación cognitiva clínica." }, { title: "Progreso local", description: "Las rachas y el historial se quedan en el navegador para mostrar el progreso sin cuenta ni latencia de red." }], faqTitle: "Preguntas sobre entrenamiento de memoria", returnAll: "Volver a todas las categorías", startDrill: "Empezar ejercicio de memoria", breadcrumbHome: "Inicio", breadcrumbDrills: "Ejercicios", breadcrumbCurrent: "Entrenamiento de memoria" },
  fr: { locale: "fr_FR", language: "fr-FR", title: "Tests de Mémoire et Entraînement", description: "Tests gratuits de mémoire à court terme, de travail et spatiale. Entraînez les nombres, motifs et itinéraires directement dans le navigateur.", keywords: ["test de mémoire", "entraînement mémoire", "mémoire de travail", "mémoire à court terme", "mémoire spatiale", "empan de chiffres", "test mémoire visuelle", "jeux de mémoire en ligne"], h1: "Tests de Mémoire et Entraînement", intro: "Choisissez un exercice dans le navigateur pour rappeler des nombres, des mots, des séquences visuelles, mettre à jour la mémoire de travail ou suivre des itinéraires. Comparez les séances dans les mêmes conditions.", drillsHeading: "Exercices de mémoire", viewAll: "Tout voir", domainsTitle: "Domaines de l'entraînement de la mémoire", drill: "Exercice", drills: "Exercices", hardwareTitle: "Conditions du navigateur, de l'écran et de l'entrée", hardware: [{ title: "Moment du stimulus", description: "Les tâches locales utilisent des horloges haute résolution, mais l'image affichée et la programmation du navigateur peuvent influencer le résultat." }, { title: "Charge adaptative", description: "Les niveaux progressifs facilitent la comparaison dans une tâche, sans produire un score cognitif clinique." }, { title: "Progression locale", description: "Les séries et l'historique restent dans le navigateur pour afficher vos progrès sans compte ni latence réseau." }], faqTitle: "Questions sur l'entraînement de la mémoire", returnAll: "Retour à toutes les catégories", startDrill: "Commencer un exercice de mémoire", breadcrumbHome: "Accueil", breadcrumbDrills: "Exercices", breadcrumbCurrent: "Entraînement de la mémoire" }
};

const CATEGORIES = {
  en: [["Short-term memory", "Hold numbers, words, colours, and short sequences briefly before recalling them."], ["Working memory", "Update information while following a rule, matching a sequence, or managing changing mental load."], ["Spatial memory", "Remember positions, paths, and visual layouts as locations and order change."]],
  ko: [["단기기억", "숫자·단어·색과 짧은 순서를 잠시 유지한 뒤 정확하게 회상합니다."], ["작업기억", "규칙을 따르고 순서를 맞추며 바뀌는 정보를 머릿속에서 갱신합니다."], ["공간기억", "위치와 순서가 바뀌는 동안 좌표·경로·시각 배치를 기억합니다."]],
  ja: [["短期記憶", "数字、単語、色、短い順序を一時的に保ち、正確に思い出します。"], ["ワーキングメモリ", "ルールを守り、順序を合わせながら変化する情報を頭の中で更新します。"], ["空間記憶", "位置や順序が変わる中で、座標、経路、視覚的な配置を覚えます。"]],
  de: [["Kurzzeitgedächtnis", "Halte Zahlen, Wörter, Farben und kurze Reihenfolgen kurz fest und rufe sie anschließend ab."], ["Arbeitsgedächtnis", "Aktualisiere Informationen, während du Regeln, Reihenfolgen und wechselnde mentale Belastung bewältigst."], ["Räumliches Gedächtnis", "Merke dir Positionen, Wege und visuelle Anordnungen, während sich Ort und Reihenfolge ändern."]],
  pt: [["Memória de curto prazo", "Mantenha números, palavras, cores e sequências curtas por um momento antes de recordá-los."], ["Memória de trabalho", "Atualize informações enquanto segue regras, combina sequências e lida com uma carga mental variável."], ["Memória espacial", "Lembre posições, caminhos e layouts visuais enquanto os locais e a ordem mudam."]],
  es: [["Memoria a corto plazo", "Mantén números, palabras, colores y secuencias breves antes de recordarlos con precisión."], ["Memoria de trabajo", "Actualiza información mientras sigues reglas, comparas secuencias y gestionas una carga mental cambiante."], ["Memoria espacial", "Recuerda posiciones, rutas y diseños visuales mientras cambian el lugar y el orden."]],
  fr: [["Mémoire à court terme", "Gardez brièvement des nombres, mots, couleurs et courtes séquences avant de les rappeler."], ["Mémoire de travail", "Mettez à jour les informations en suivant des règles, des séquences et une charge mentale variable."], ["Mémoire spatiale", "Retenez des positions, des parcours et des dispositions visuelles quand le lieu et l'ordre changent."]]
};

const DRILL_SLUGS = ["short-term-memory/digit-span", "short-term-memory/word-recall", "short-term-memory/color-sequence", "working-memory/n-back", "spatial-memory/grid-memorization", "spatial-memory/path-tracing", "spatial-memory/object-location"];
const DRILL_NAMES = {
  en: ["Digit Span", "Word Recall", "Color Sequence", "N-Back", "Grid Memorization", "Path Tracing", "Object Location"],
  ko: ["숫자 기억", "단어 회상", "색 순서 기억", "N-back", "격자 기억", "경로 추적 기억", "물체 위치 기억"],
  ja: ["数字記憶", "単語記憶", "色の順序記憶", "Nバック", "グリッド記憶", "経路記憶", "物体位置記憶"],
  de: ["Zahlenspanne", "Wortabruf", "Farbfolge", "N-Back", "Gitter-Merken", "Pfadverfolgung", "Objektposition"],
  pt: ["Span de Dígitos", "Recordação de Palavras", "Sequência de Cores", "N-Back", "Memorização de Grade", "Memória de Caminhos", "Localização de Objetos"],
  es: ["Span de Dígitos", "Recuerdo de Palabras", "Secuencia de Colores", "N-Back", "Memorización de Cuadrícula", "Recorrido de Rutas", "Ubicación de Objetos"],
  fr: ["Empan de chiffres", "Rappel de mots", "Séquence de couleurs", "N-Back", "Mémorisation de grille", "Suivi de parcours", "Emplacement des objets"]
};

export function getMemoryHubUi(locale = "en") { return { ...(UI[locale] || UI.en), categories: (CATEGORIES[locale] || CATEGORIES.en).map(([name, description]) => ({ name, description })) }; }
export function getMemoryHubFaqs(locale = "en") { return (FAQS[locale] || FAQS.en).map(([q, a]) => ({ q, a })); }
export function buildMemoryHubSeo(locale, url, languages) {
  const ui = getMemoryHubUi(locale);
  const faqs = getMemoryHubFaqs(locale);
  const names = DRILL_NAMES[locale] || DRILL_NAMES.en;
  const base = "https://skilldrills.online";
  const localePrefix = locale === "en" ? "" : `/${locale}`;
  const itemList = DRILL_SLUGS.map((slug, i) => ({ "@type": "ListItem", position: i + 1, name: names[i], url: `${base}${localePrefix}/drills/memory/${slug}` }));
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: ui.breadcrumbHome, item: `${base}${localePrefix || "/"}` }, { "@type": "ListItem", position: 2, name: ui.breadcrumbDrills, item: `${base}${localePrefix}/drills` }, { "@type": "ListItem", position: 3, name: ui.breadcrumbCurrent, item: url }] };
  const collectionPageSchema = { "@context": "https://schema.org", "@type": "CollectionPage", name: ui.title, url, description: ui.description, inLanguage: ui.language, isAccessibleForFree: true, author: { "@type": "Organization", name: "SkillDrills", url: base }, sameAs: ["https://en.wikipedia.org/wiki/Working_memory", "https://en.wikipedia.org/wiki/Short-term_memory", "https://en.wikipedia.org/wiki/Spatial_memory"], mainEntity: { "@type": "ItemList", numberOfItems: itemList.length, itemListElement: itemList } };
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ q, a }) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) };
  return { metadata: { title: `${ui.title} | SkillDrills`, description: ui.description, keywords: ui.keywords, robots: { index: true, follow: true }, alternates: { canonical: url, languages }, openGraph: { title: `${ui.title} | SkillDrills`, description: ui.description, url, siteName: "SkillDrills", type: "website", locale: ui.locale, images: [{ url: `${base}/icons/icon-512x512.png`, width: 512, height: 512, alt: ui.title }] }, twitter: { card: "summary_large_image", title: `${ui.title} | SkillDrills`, description: ui.description, images: [`${base}/icons/icon-512x512.png`] } }, breadcrumbSchema, collectionPageSchema, faqSchema };
}
