const FAQS = {
  en: [
    ["What is reaction speed training?", "Reaction speed training uses repeatable visual, decision, and motor-response tasks to practise noticing a signal and responding without anticipation. SkillDrills separates simple clicks, visual scanning, and moving-target drills so you can choose the task that matches your goal."],
    ["How can I improve my visual reaction time?", "Use short, repeatable sessions, wait for the real signal instead of guessing, and compare results under the same device and display conditions. Sleep, attention, input latency, and practice structure all affect a browser result."],
    ["What is a normal visual reaction time?", "Studies of simple visual reaction time commonly report roughly 200 to 250 ms for healthy adults (Kosinski, 2008; Woods et al., 2015). A browser result adds display refresh, input latency and the click itself, so it usually reads higher; treat one score as a personal baseline, not a medical norm."],
    ["What is the difference between a reaction test and a reflex drill?", "A simple reaction test asks for one response to one signal. A reflex drill may add distractors, choices, moving targets, or repeated direction changes, so it also exercises attention and visual decision-making."],
    ["Which drill should I start with?", "Start with Reaction Time Test for a simple baseline. Choose Reflex Training Drill or Reaction Game for repeated stimulus responses, Saccadic Gallery for rapid visual shifts, and the tracking drills when moving targets are your priority."],
    ["Can these drills help gaming or esports practice?", "They provide browser practice for visual response, target acquisition, and tracking situations that appear in games. Transfer depends on the game, player, device, and broader practice; no page can guarantee a competitive improvement."],
    ["Do the reaction drills work on mobile?", "The category pages are responsive, but a touchscreen, browser, refresh rate, and input method change the task. Use a desktop mouse or keyboard when you want more comparable click-latency results."],
    ["How do display and input latency affect a score?", "A result includes the time from the rendered signal to the input event, not just brain processing. Refresh rate, browser scheduling, pointer hardware, operating-system settings, and network-independent local rendering can all change the number."],
    ["How long should a reaction-training session be?", "Use a few focused rounds and pause when attention or visual comfort drops. Consistent five-to-ten-minute practice blocks are easier to compare than a long session affected by fatigue."],
    ["Are these reaction tests diagnostic?", "No. They are free browser exercises and personal practice tools. They do not diagnose neurological, visual, or motor conditions; recurring symptoms or concerns should be discussed with an appropriate professional."]
  ],
  ko: [
    ["반응속도 훈련은 무엇인가요?", "반응속도 훈련은 신호를 보고 예상하지 않은 상태에서 선택하거나 클릭하는 과제를 반복하는 연습입니다. 이 페이지에서는 단순 반응, 시각 탐색, 움직이는 표적 과제를 나누어 목적에 맞게 고를 수 있습니다."],
    ["시각 반응속도를 어떻게 높일 수 있나요?", "짧고 반복 가능한 세션을 사용하고 신호가 오기 전에 추측해서 누르지 마세요. 수면, 집중도, 입력 지연, 화면 조건과 연습 방식이 브라우저 결과에 영향을 줍니다."],
    ["정상적인 시각 반응속도는 얼마인가요?", "브라우저 반응 테스트 결과는 시각 처리뿐 아니라 화면 주사율, 기기 지연, 브라우저와 클릭 동작의 영향을 받습니다. 한 번의 점수를 의학적 기준으로 보지 말고 같은 조건의 개인 기록을 비교하세요."],
    ["반응 테스트와 반사신경 훈련의 차이는 무엇인가요?", "단순 반응 테스트는 하나의 신호에 하나의 동작으로 답합니다. 반사신경 훈련은 방해 자극, 선택, 움직이는 표적이나 방향 변화를 더해 주의력과 시각 판단도 함께 연습합니다."],
    ["어떤 드릴부터 시작하면 좋나요?", "기준 기록은 반응시간 테스트로 시작하세요. 반복 자극은 반사 훈련이나 반응 게임, 빠른 시선 이동은 사케드 갤러리, 움직이는 표적은 추적 훈련을 선택하면 됩니다."],
    ["게임이나 e스포츠 연습에 도움이 되나요?", "시각 반응, 표적 획득, 움직이는 대상 추적과 비슷한 화면 과제를 연습할 수 있습니다. 실제 전이는 게임과 장비, 개인 훈련에 따라 다르며 향상을 보장하지 않습니다."],
    ["모바일에서도 사용할 수 있나요?", "페이지는 반응형이지만 터치 화면, 브라우저, 주사율과 입력 방식이 과제를 바꿉니다. 클릭 지연을 비교하려면 데스크톱 마우스나 키보드가 더 일정합니다."],
    ["화면과 입력 지연이 점수에 영향을 주나요?", "결과에는 신호가 화면에 그려진 뒤 입력 이벤트가 들어오는 시간도 포함됩니다. 주사율, 브라우저 스케줄링, 마우스, 운영체제 설정이 수치를 바꿀 수 있습니다."],
    ["반응 훈련은 얼마나 오래 해야 하나요?", "집중이 유지되는 짧은 라운드를 사용하고 눈이나 주의가 피로해지면 쉬세요. 5~10분의 일정한 블록이 피로가 쌓인 긴 세션보다 비교하기 쉽습니다."],
    ["이 반응 테스트가 진단 도구인가요?", "아닙니다. 무료 브라우저 연습과 개인 기록 도구입니다. 신경계나 시각, 운동 기능을 진단하지 않으며 반복되는 증상이나 걱정은 적절한 전문가에게 상담하세요."]
  ],
  ja: [
    ["反応速度トレーニングとは何ですか？", "反応速度トレーニングは、合図を見て予測せずに選択やクリックを行う課題を繰り返す練習です。ここでは単純反応、視覚探索、動く標的の課題を分けて選べます。"],
    ["視覚反応速度を上げるにはどうすればよいですか？", "短く繰り返せるセッションを使い、合図の前に予測して押さないことが基本です。睡眠、集中、入力遅延、画面条件、練習方法がブラウザの結果に影響します。"],
    ["通常の視覚反応速度はどのくらいですか？", "ブラウザの反応テストは視覚処理だけでなく、画面のリフレッシュレート、機器の遅延、ブラウザ、クリック動作の影響を受けます。一度の数値を医学的な基準にせず、同じ条件の自分の記録を比べてください。"],
    ["反応テストと反射神経ゲームの違いは何ですか？", "単純な反応テストは一つの合図に一つの動作で答えます。反射神経ゲームや訓練では、妨害刺激、選択、動く標的、方向変化が加わり、注意と視覚判断も使います。"],
    ["どのドリルから始めればよいですか？", "基準を知りたいなら反応速度テストから始めます。反復刺激は反射神経トレーニングや反応ゲーム、素早い視線移動はサッケード・ギャラリー、動く標的は追跡系を選んでください。"],
    ["ゲームやeスポーツの練習に役立ちますか？", "視覚反応、標的の取得、動く対象の追跡に似た画面課題を練習できます。ただし実際の転移はゲーム、機器、個人の練習によって異なり、向上を保証するものではありません。"],
    ["スマートフォンでも使えますか？", "ページはレスポンシブですが、タッチ画面、ブラウザ、リフレッシュレート、入力方法で課題は変わります。クリック遅延を比べるならデスクトップのマウスやキーボードが安定します。"],
    ["画面や入力遅延は記録に影響しますか？", "記録には合図が画面に表示されてから入力イベントが届くまでの時間も含まれます。リフレッシュレート、ブラウザの処理、マウス、OS設定で数値は変わります。"],
    ["反応速度の練習はどのくらい行えばよいですか？", "集中できる短いラウンドを使い、目や注意が疲れたら休みます。5〜10分の一定したブロックのほうが、疲労が混ざる長時間セッションより比較しやすいです。"],
    ["この反応テストは診断に使えますか？", "いいえ。無料のブラウザ練習と個人記録のためのツールです。神経、視覚、運動機能を診断するものではないため、症状や不安が続く場合は専門家に相談してください。"]
  ],
  de: [
    ["Was ist Reaktionstraining?", "Reaktionstraining wiederholt visuelle, entscheidungsbezogene und motorische Aufgaben, bei denen ein Signal erkannt und ohne Vorwegnahme beantwortet wird. Hier sind einfache Klicks, visuelle Suche und bewegte Ziele getrennt."],
    ["Wie verbessere ich meine visuelle Reaktionszeit?", "Nutze kurze, wiederholbare Sessions und reagiere erst auf das echte Signal. Schlaf, Aufmerksamkeit, Eingabelatenz, Bildschirm und Übungsaufbau beeinflussen das Ergebnis im Browser."],
    ["Was ist eine normale visuelle Reaktionszeit?", "Ein Browser-Test hängt nicht nur von der visuellen Verarbeitung ab, sondern auch von Bildrate, Gerät, Browser und Klick. Vergleiche wiederholte Werte unter gleichen Bedingungen statt einen medizinischen Normwert anzunehmen."],
    ["Was ist der Unterschied zwischen Reaktionstest und Reflexübung?", "Ein einfacher Reaktionstest verlangt eine Antwort auf ein Signal. Eine Reflexübung ergänzt Ablenkungen, Auswahl, bewegte Ziele oder Richtungswechsel und fordert dadurch auch Aufmerksamkeit und visuelle Entscheidung."],
    ["Mit welchem Drill sollte ich beginnen?", "Beginne mit Reaction Time Test für eine einfache Basis. Nutze Reflex Training oder Reaction Game für wiederholte Signale, Saccadic Gallery für schnelle Blicksprünge und Tracking-Drills für bewegte Ziele."],
    ["Hilft das für Gaming oder E-Sport?", "Die Übungen bieten Browserpraxis für visuelle Reaktion, Zielaufnahme und bewegte Ziele. Der Transfer hängt von Spiel, Gerät und Gesamttraining ab und ist nicht garantiert."],
    ["Funktionieren die Drills auf dem Smartphone?", "Die Seiten sind responsiv, aber Touchscreen, Browser, Bildrate und Eingabemethode verändern die Aufgabe. Für vergleichbarere Klickwerte ist eine Desktop-Maus oder Tastatur geeigneter."],
    ["Wie beeinflussen Display- und Eingabelatenz den Wert?", "Der Wert enthält die Zeit vom gerenderten Signal bis zum Eingabeereignis. Bildrate, Browserplanung, Maus, Betriebssystem und Geräteeinstellungen können die Zahl verändern."],
    ["Wie lange sollte eine Reaktionssession dauern?", "Nutze einige konzentrierte Runden und pausiere bei nachlassender Aufmerksamkeit oder visueller Belastung. Gleichmäßige Blöcke von fünf bis zehn Minuten lassen sich besser vergleichen."],
    ["Sind diese Reaktionstests diagnostisch?", "Nein. Sie sind kostenlose Browserübungen und persönliche Trainingshilfen. Sie diagnostizieren keine neurologischen, visuellen oder motorischen Erkrankungen; wiederkehrende Beschwerden gehören fachlich abgeklärt."]
  ],
  pt: [
    ["O que é treino de tempo de reação?", "O treino de tempo de reação repete tarefas visuais, de decisão e de resposta motora para reconhecer um sinal e agir sem antecipá-lo. Aqui você encontra cliques simples, busca visual e alvos em movimento."],
    ["Como melhorar meu tempo de reação visual?", "Use sessões curtas e repetíveis e espere o sinal verdadeiro em vez de tentar adivinhar. Sono, atenção, latência de entrada, tela e estrutura do treino alteram o resultado no navegador."],
    ["Qual é um tempo de reação visual normal?", "Um teste no navegador depende do processamento visual, da taxa de atualização, do dispositivo, do navegador e do clique. Compare seus próprios testes em condições iguais em vez de tratar um número como norma médica."],
    ["Qual a diferença entre teste de reação e treino de reflexo?", "Um teste simples pede uma resposta a um sinal. Um treino de reflexo pode adicionar distrações, escolhas, alvos móveis ou mudanças de direção, exigindo também atenção e decisão visual."],
    ["Por qual treino devo começar?", "Comece pelo Reaction Time Test para uma base simples. Use Reflex Training ou Reaction Game para estímulos repetidos, Saccadic Gallery para mudanças rápidas do olhar e os treinos de rastreamento para alvos móveis."],
    ["Isso ajuda no gaming ou nos esports?", "Os exercícios oferecem prática de resposta visual, aquisição de alvo e acompanhamento de objetos móveis. A transferência depende do jogo, equipamento e treino geral, portanto não é garantida."],
    ["Os treinos funcionam no celular?", "As páginas são responsivas, mas toque, navegador, frequência da tela e método de entrada mudam a tarefa. Para comparar cliques com mais consistência, prefira mouse ou teclado no computador."],
    ["Como a latência da tela e da entrada afeta o resultado?", "O resultado inclui o tempo entre o sinal renderizado e o evento de entrada. Frequência, navegador, mouse, sistema operacional e configurações do dispositivo podem mudar o número."],
    ["Quanto deve durar uma sessão?", "Faça algumas rodadas concentradas e descanse quando a atenção ou o conforto visual cair. Blocos consistentes de cinco a dez minutos são mais fáceis de comparar que sessões longas com fadiga."],
    ["Esses testes são diagnósticos?", "Não. São exercícios gratuitos no navegador e ferramentas de prática pessoal. Não diagnosticam condições neurológicas, visuais ou motoras; sintomas recorrentes devem ser avaliados por um profissional."]
  ],
  es: [
    ["¿Qué es el entrenamiento del tiempo de reacción?", "Repite tareas visuales, de decisión y de respuesta motora para reconocer una señal y actuar sin anticiparla. Aquí se separan los clics simples, la búsqueda visual y los objetivos móviles."],
    ["¿Cómo mejoro mi tiempo de reacción visual?", "Usa sesiones cortas y repetibles y espera la señal real en lugar de adivinar. El sueño, la atención, la latencia de entrada, la pantalla y la estructura del entrenamiento cambian el resultado."],
    ["¿Cuál es un tiempo de reacción visual normal?", "Un test de navegador depende del procesamiento visual, la frecuencia de pantalla, el dispositivo, el navegador y el clic. Compara tus propios resultados en condiciones iguales, no un único número como norma médica."],
    ["¿Qué diferencia hay entre un test de reacción y un ejercicio de reflejos?", "El test simple pide una respuesta a una señal. El ejercicio puede añadir distractores, elecciones, objetivos móviles o cambios de dirección, y requiere también atención y decisión visual."],
    ["¿Con qué ejercicio debo empezar?", "Empieza con Reaction Time Test para una base sencilla. Usa Reflex Training o Reaction Game para estímulos repetidos, Saccadic Gallery para cambios rápidos de mirada y los ejercicios de seguimiento para objetivos móviles."],
    ["¿Ayuda para gaming o esports?", "Ofrece práctica de respuesta visual, adquisición de objetivos y seguimiento de objetos móviles. La transferencia depende del juego, el equipo y el entrenamiento global, así que no está garantizada."],
    ["¿Funcionan los ejercicios en móvil?", "Las páginas son adaptables, pero la pantalla táctil, el navegador, la frecuencia y el método de entrada cambian la tarea. Para comparar clics con más consistencia, usa ratón o teclado en ordenador."],
    ["¿Cómo afecta la latencia de pantalla y entrada al resultado?", "El resultado incluye el tiempo desde la señal dibujada hasta el evento de entrada. La frecuencia, el navegador, el ratón, el sistema y los ajustes del dispositivo pueden cambiar la cifra."],
    ["¿Cuánto debe durar una sesión?", "Haz unas rondas concentradas y descansa cuando baje la atención o el confort visual. Los bloques constantes de cinco a diez minutos se comparan mejor que una sesión larga con fatiga."],
    ["¿Son diagnósticos estos tests de reacción?", "No. Son ejercicios gratuitos del navegador y herramientas de práctica personal. No diagnostican problemas neurológicos, visuales o motores; los síntomas repetidos deben valorarse profesionalmente."]
  ],
  fr: [
    ["Qu'est-ce que l'entraînement du temps de réaction ?", "Il répète des tâches visuelles, décisionnelles et motrices pour reconnaître un signal et répondre sans l'anticiper. La page sépare clic simple, recherche visuelle et cible mobile."],
    ["Comment améliorer mon temps de réaction visuel ?", "Utilisez des séances courtes et répétables et attendez le vrai signal au lieu de deviner. Sommeil, attention, latence d'entrée, écran et structure de l'exercice modifient le résultat."],
    ["Quel est un temps de réaction visuel normal ?", "Un test dans le navigateur dépend du traitement visuel, du taux de rafraîchissement, du matériel, du navigateur et du clic. Comparez vos propres essais dans les mêmes conditions plutôt qu'un nombre présenté comme norme médicale."],
    ["Quelle différence entre test de réaction et exercice de réflexes ?", "Un test simple demande une réponse à un signal. Un exercice de réflexes peut ajouter distracteurs, choix, cibles mobiles ou changements de direction, et solliciter aussi l'attention et la décision visuelles."],
    ["Par quel exercice commencer ?", "Commencez par Reaction Time Test pour une base simple. Choisissez Reflex Training ou Reaction Game pour les stimuli répétés, Saccadic Gallery pour les changements rapides du regard et les exercices de suivi pour les cibles mobiles."],
    ["Cela aide-t-il pour le jeu vidéo ou l'e-sport ?", "Ces exercices offrent une pratique de la réponse visuelle, de l'acquisition de cible et du suivi d'objets mobiles. Le transfert dépend du jeu, du matériel et de l'entraînement global ; il n'est pas garanti."],
    ["Les exercices fonctionnent-ils sur mobile ?", "Les pages sont responsives, mais le tactile, le navigateur, la fréquence d'affichage et le mode d'entrée changent la tâche. Pour comparer les clics, une souris ou un clavier d'ordinateur est plus constant."],
    ["Comment la latence de l'écran et de l'entrée influence-t-elle le résultat ?", "Le résultat inclut le délai entre le signal affiché et l'événement d'entrée. Fréquence, navigateur, souris, système et réglages de l'appareil peuvent modifier le chiffre."],
    ["Combien de temps doit durer une séance ?", "Faites quelques séries concentrées et faites une pause si l'attention ou le confort visuel baisse. Des blocs réguliers de cinq à dix minutes se comparent mieux qu'une longue séance fatigante."],
    ["Ces tests de réaction sont-ils diagnostiques ?", "Non. Ce sont des exercices gratuits dans le navigateur et des outils de pratique personnelle. Ils ne diagnostiquent pas une affection neurologique, visuelle ou motrice ; les symptômes récurrents doivent être évalués par un professionnel."]
  ]
};

const UI = {
  en: { locale: "en_US", language: "en-US", title: "Reaction Time Tests & Reflex Training", description: "Free reaction time tests and reflex drills for visual response, click speed, saccadic shifts, and moving-target tracking. Practise in your browser.", keywords: ["reaction time test", "reaction speed training", "reflex training", "visual reaction test", "click speed test", "moving target tracking", "saccadic eye training", "reaction drills online"], h1: "Reaction Time Tests & Reflex Training", intro: "Choose a focused browser drill for simple reaction time, visual decision speed, saccadic shifts, or moving-target tracking. Compare repeatable sessions under the same device conditions.", drillsHeading: "Reaction drills", viewAll: "View all", domainsTitle: "Reaction training domains", drill: "Drill", drills: "Drills", hardwareTitle: "Browser, display & input conditions", hardware: [{ title: "Signal timing", description: "Local browser tasks use high-resolution performance clocks, but the displayed frame and browser scheduling still affect a result." }, { title: "Input path", description: "Mouse, keyboard, touchscreen, operating system, and pointer settings change when an input event reaches the page." }, { title: "Display refresh", description: "A higher refresh rate can reduce visual frame quantization, but it does not turn a browser score into a clinical reaction measurement." }], faqTitle: "Reaction training questions", returnAll: "Return to all drill categories", startTest: "Start Reaction Time Test", breadcrumbHome: "Home", breadcrumbDrills: "Drills", breadcrumbCurrent: "Reaction training" },
  ko: { locale: "ko_KR", language: "ko-KR", title: "반응속도 테스트와 반사신경 훈련", description: "시각 반응, 클릭 속도, 빠른 시선 이동과 움직이는 표적을 연습하는 무료 반응속도 테스트와 반사신경 드릴입니다.", keywords: ["반응속도 테스트", "반사신경 테스트", "반응속도 훈련", "시각 반응 테스트", "클릭 속도 테스트", "동체시력 훈련", "시선 이동 훈련", "반응 훈련 온라인"], h1: "반응속도 테스트와 반사신경 훈련", intro: "단순 반응속도, 시각 판단, 빠른 시선 이동, 움직이는 표적 추적 중 원하는 브라우저 드릴을 선택하세요. 같은 기기 조건에서 세션을 비교할 수 있습니다.", drillsHeading: "반응 훈련 드릴", viewAll: "전체 보기", domainsTitle: "반응 훈련 분야", drill: "드릴", drills: "드릴", hardwareTitle: "브라우저·화면·입력 조건", hardware: [{ title: "신호 표시 시간", description: "브라우저는 고해상도 시계를 사용하지만 실제 화면 프레임과 브라우저 스케줄링이 결과에 영향을 줍니다." }, { title: "입력 경로", description: "마우스, 키보드, 터치, 운영체제와 포인터 설정에 따라 입력 이벤트가 페이지에 도착하는 시간이 달라집니다." }, { title: "화면 주사율", description: "높은 주사율은 프레임 단위의 시각 지연을 줄일 수 있지만 브라우저 기록을 임상 반응 측정으로 만들지는 않습니다." }], faqTitle: "반응 훈련 자주 묻는 질문", returnAll: "전체 드릴 카테고리로 돌아가기", startTest: "반응속도 테스트 시작", breadcrumbHome: "홈", breadcrumbDrills: "드릴", breadcrumbCurrent: "반응 훈련" },
  ja: { locale: "ja_JP", language: "ja-JP", title: "反応速度テストと反射神経トレーニング", description: "視覚反応、クリック速度、素早い視線移動、動く標的を練習できる無料の反応速度テスト集です。ブラウザですぐ使えます。", keywords: ["反応速度 テスト", "反射神経 テスト", "反応速度 トレーニング", "視覚反応 テスト", "クリック速度 テスト", "動体視力 トレーニング", "眼球運動 練習", "反応ゲーム オンライン"], h1: "反応速度テストと反射神経トレーニング", intro: "単純反応、視覚判断、素早い視線移動、動く標的の追跡から目的に合うブラウザ練習を選べます。同じ機器条件でセッションを比べてください。", drillsHeading: "反応トレーニング", viewAll: "すべて見る", domainsTitle: "反応トレーニングの分野", drill: "ドリル", drills: "ドリル", hardwareTitle: "ブラウザ・画面・入力条件", hardware: [{ title: "合図の表示時間", description: "ブラウザは高精度の時計を使いますが、実際の表示フレームと処理のタイミングは結果に影響します。" }, { title: "入力経路", description: "マウス、キーボード、タッチ、OSやポインター設定によって入力イベントの到着時間は変わります。" }, { title: "リフレッシュレート", description: "高いリフレッシュレートは表示の量子化を減らせますが、ブラウザの記録が臨床測定になるわけではありません。" }], faqTitle: "反応トレーニングのよくある質問", returnAll: "すべてのドリルカテゴリへ戻る", startTest: "反応速度テストを始める", breadcrumbHome: "ホーム", breadcrumbDrills: "ドリル", breadcrumbCurrent: "反応トレーニング" },
  de: { locale: "de_DE", language: "de-DE", title: "Reaktionstest & Reflextraining", description: "Kostenlose Reaktionstests und Reflexübungen für visuelle Reaktion, Klicktempo, Blicksprünge und bewegte Ziele direkt im Browser.", keywords: ["Reaktionstest", "Reaktionszeit testen", "Reflextraining", "visueller Reaktionstest", "Klickgeschwindigkeit testen", "dynamisches Sehen", "Sakkaden trainieren", "Reaktionsübungen online"], h1: "Reaktionstest & Reflextraining", intro: "Wähle eine Browserübung für einfache Reaktionszeit, visuelle Entscheidung, schnelle Blicksprünge oder bewegte Ziele. Vergleiche Sessions unter denselben Gerätebedingungen.", drillsHeading: "Reaktionsübungen", viewAll: "Alle anzeigen", domainsTitle: "Bereiche des Reaktionstrainings", drill: "Drill", drills: "Drills", hardwareTitle: "Browser-, Display- und Eingabebedingungen", hardware: [{ title: "Signalzeitpunkt", description: "Lokale Browseraufgaben verwenden hochauflösende Performance-Uhren, aber Anzeigeframe und Browserplanung beeinflussen den Wert." }, { title: "Eingabepfad", description: "Maus, Tastatur, Touchscreen, Betriebssystem und Pointer-Einstellungen verändern den Eingang eines Events." }, { title: "Bildwiederholrate", description: "Eine höhere Rate kann die Frame-Quantisierung verringern, macht den Browserwert aber nicht zu einer klinischen Reaktionsmessung." }], faqTitle: "Fragen zum Reaktionstraining", returnAll: "Zu allen Drill-Kategorien", startTest: "Reaktionstest starten", breadcrumbHome: "Startseite", breadcrumbDrills: "Drills", breadcrumbCurrent: "Reaktionstraining" },
  pt: { locale: "pt_BR", language: "pt-BR", title: "Testes de Reação e Treino de Reflexos", description: "Testes de reação e treinos de reflexo grátis para resposta visual, velocidade de clique, movimentos sacádicos e alvos móveis no navegador.", keywords: ["teste de tempo de reação", "treino de reflexo", "teste de reação visual", "teste de velocidade de clique", "visão dinâmica", "treino de sacadas", "rastreamento de alvo", "exercícios de reação online"], h1: "Testes de Reação e Treino de Reflexos", intro: "Escolha um treino no navegador para reação simples, decisão visual, movimentos rápidos do olhar ou rastreamento de alvos móveis. Compare sessões nas mesmas condições do dispositivo.", drillsHeading: "Treinos de reação", viewAll: "Ver todos", domainsTitle: "Áreas do treino de reação", drill: "Treino", drills: "Treinos", hardwareTitle: "Condições do navegador, tela e entrada", hardware: [{ title: "Momento do sinal", description: "As tarefas locais usam relógios de alta resolução, mas o quadro exibido e o agendamento do navegador afetam o resultado." }, { title: "Caminho da entrada", description: "Mouse, teclado, toque, sistema operacional e configurações do ponteiro mudam quando o evento chega à página." }, { title: "Frequência da tela", description: "Uma frequência maior pode reduzir a quantização dos quadros, mas não transforma o resultado em medida clínica." }], faqTitle: "Dúvidas sobre treino de reação", returnAll: "Voltar a todas as categorias", startTest: "Começar teste de reação", breadcrumbHome: "Início", breadcrumbDrills: "Treinos", breadcrumbCurrent: "Treino de reação" },
  es: { locale: "es_ES", language: "es-ES", title: "Tests de Reacción y Entrenamiento de Reflejos", description: "Tests de reacción y ejercicios de reflejos gratis para respuesta visual, velocidad de clic, movimientos sacádicos y objetivos móviles.", keywords: ["test de tiempo de reacción", "entrenamiento de reflejos", "test de reacción visual", "test de velocidad de clic", "visión dinámica", "entrenamiento sacádico", "seguimiento de objetivos", "ejercicios de reacción online"], h1: "Tests de Reacción y Entrenamiento de Reflejos", intro: "Elige un ejercicio de navegador para reacción simple, decisión visual, movimientos rápidos de la mirada o seguimiento de objetivos móviles. Compara sesiones con el mismo dispositivo.", drillsHeading: "Ejercicios de reacción", viewAll: "Ver todos", domainsTitle: "Áreas del entrenamiento de reacción", drill: "Ejercicio", drills: "Ejercicios", hardwareTitle: "Condiciones del navegador, pantalla y entrada", hardware: [{ title: "Momento de la señal", description: "Las tareas locales usan relojes de alta resolución, pero el fotograma mostrado y la planificación del navegador afectan al resultado." }, { title: "Ruta de entrada", description: "Ratón, teclado, pantalla táctil, sistema operativo y ajustes del puntero cambian cuándo llega el evento a la página." }, { title: "Frecuencia de pantalla", description: "Una frecuencia mayor puede reducir la cuantización de fotogramas, pero no convierte el resultado en una medición clínica." }], faqTitle: "Preguntas sobre entrenamiento de reacción", returnAll: "Volver a todas las categorías", startTest: "Empezar test de reacción", breadcrumbHome: "Inicio", breadcrumbDrills: "Ejercicios", breadcrumbCurrent: "Entrenamiento de reacción" },
  fr: { locale: "fr_FR", language: "fr-FR", title: "Tests de Réaction et Entraînement des Réflexes", description: "Tests de réaction et exercices de réflexes gratuits pour réponse visuelle, vitesse de clic, mouvements saccadiques et cibles mobiles.", keywords: ["test temps de réaction", "entraînement réflexes", "test réaction visuelle", "test vitesse de clic", "poursuite oculaire", "entraînement saccadique", "suivi de cible", "exercices réaction en ligne"], h1: "Tests de Réaction et Entraînement des Réflexes", intro: "Choisissez un exercice dans le navigateur pour la réaction simple, la décision visuelle, les déplacements rapides du regard ou le suivi de cibles mobiles. Comparez les séances dans les mêmes conditions.", drillsHeading: "Exercices de réaction", viewAll: "Tout voir", domainsTitle: "Domaines de l'entraînement de la réaction", drill: "Exercice", drills: "Exercices", hardwareTitle: "Conditions du navigateur, de l'écran et de l'entrée", hardware: [{ title: "Moment du signal", description: "Les tâches locales utilisent des horloges haute résolution, mais l'image affichée et la programmation du navigateur influencent le résultat." }, { title: "Chaîne d'entrée", description: "Souris, clavier, tactile, système et réglages du pointeur changent l'arrivée de l'événement dans la page." }, { title: "Fréquence d'affichage", description: "Une fréquence plus élevée peut réduire la quantification des images, sans transformer le résultat en mesure clinique." }], faqTitle: "Questions sur l'entraînement de la réaction", returnAll: "Retour à toutes les catégories", startTest: "Commencer le test de réaction", breadcrumbHome: "Accueil", breadcrumbDrills: "Exercices", breadcrumbCurrent: "Entraînement de la réaction" }
};

const CATEGORY_COPY = {
  en: [{ name: "Simple latency & reflexes", description: "Measure simple response time and practise fast visual-to-motor reactions." }, { name: "Saccadic eye reflexes", description: "Practise rapid gaze shifts, corner checks, and visual target acquisition." }, { name: "Dynamic pursuit & tracking", description: "Follow moving targets and respond when visual direction or speed changes." }],
  ko: [{ name: "단순 반응속도와 반사신경", description: "기본 반응시간을 확인하고 시각 신호에 빠르게 움직이는 연습을 합니다." }, { name: "사케드 시선 반응", description: "빠른 시선 이동, 코너 확인과 시각 표적 획득을 연습합니다." }, { name: "동적 추적과 표적 따라가기", description: "움직이는 표적을 따라가고 방향이나 속도 변화에 반응합니다." }],
  ja: [{ name: "単純反応と反射神経", description: "基本的な反応時間を確認し、視覚刺激への素早い動作を練習します。" }, { name: "サッケード視線反応", description: "素早い視線移動、コーナー確認、標的の取得を練習します。" }, { name: "動的追跡とターゲット追跡", description: "動く標的を追い、方向や速度の変化に反応します。" }],
  de: [{ name: "Einfache Latenz und Reflexe", description: "Miss einfache Reaktionszeit und übe schnelle visuell-motorische Antworten." }, { name: "Sakkadische Blickreaktionen", description: "Übe schnelle Blicksprünge, Eckenkontrollen und visuelle Zielaufnahme." }, { name: "Dynamische Verfolgung", description: "Folge bewegten Zielen und reagiere auf Richtungs- oder Tempowechsel." }],
  pt: [{ name: "Latência simples e reflexos", description: "Meça a resposta simples e pratique reações visuais e motoras rápidas." }, { name: "Reflexos sacádicos do olhar", description: "Pratique movimentos rápidos do olhar, checagem de cantos e aquisição visual." }, { name: "Perseguição e rastreamento dinâmico", description: "Acompanhe alvos móveis e responda a mudanças de direção ou velocidade." }],
  es: [{ name: "Latencia simple y reflejos", description: "Mide la respuesta simple y practica reacciones visuales y motoras rápidas." }, { name: "Reflejos sacádicos de la mirada", description: "Practica movimientos rápidos de mirada, comprobación de esquinas y adquisición visual." }, { name: "Seguimiento dinámico", description: "Sigue objetivos móviles y responde a cambios de dirección o velocidad." }],
  fr: [{ name: "Latence simple et réflexes", description: "Mesurez la réponse simple et pratiquez des réactions visuelles et motrices rapides." }, { name: "Réactions saccadiques du regard", description: "Pratiquez les déplacements rapides du regard, les angles et l'acquisition visuelle." }, { name: "Poursuite et suivi dynamiques", description: "Suivez des cibles mobiles et réagissez aux changements de direction ou de vitesse." }]
};

export function getReactionSpeedHubUi(locale = "en") { return { ...(UI[locale] || UI.en), categories: CATEGORY_COPY[locale] || CATEGORY_COPY.en }; }
export function getReactionSpeedHubFaqs(locale = "en") { return (FAQS[locale] || FAQS.en).map(([q, a]) => ({ q, a })); }
export function buildReactionSpeedHubSeo(locale, url, languages) {
  const ui = getReactionSpeedHubUi(locale);
  const faqs = getReactionSpeedHubFaqs(locale);
  const drillSlugs = ["reaction-time-test", "reflex-training-drill", "reaction-game", "saccadic-gallery", "market-doors-pursuit", "barrier-sequence-pursuit", "visual-tracking-speed-test", "fps-tracking-trainer"];
  const names = { en: ["Reaction Time Test", "Reflex Training Drill", "Reaction Game", "Saccadic Gallery", "Market Doors Pursuit", "Barrier Sequence Pursuit", "Visual Tracking Speed Test", "FPS Tracking Trainer"], ko: ["반응시간 테스트", "반사신경 훈련", "반응 게임", "사케드 갤러리", "마켓 도어 추적", "장벽 시퀀스 추적", "시각 추적 속도 테스트", "FPS 추적 트레이너"], ja: ["反応速度テスト", "反射神経トレーニング", "反応ゲーム", "サッケード・ギャラリー", "マーケットドア追跡", "バリアシーケンス追跡", "視覚追跡速度テスト", "FPS追跡トレーナー"], de: ["Reaktionstest", "Reflextraining", "Reaktionsspiel", "Sakkaden-Galerie", "Market-Doors-Verfolgung", "Barrier-Sequenz-Verfolgung", "Test für visuelle Verfolgung", "FPS-Tracking-Trainer"], pt: ["Teste de Tempo de Reação", "Treino de Reflexos", "Jogo de Reação", "Galeria Sacádica", "Perseguição das Portas", "Perseguição da Barreira", "Teste de Velocidade Visual", "Treino de Rastreamento FPS"], es: ["Test de Tiempo de Reacción", "Entrenamiento de Reflejos", "Juego de Reacción", "Galería Sacádica", "Seguimiento de Puertas", "Seguimiento de Barreras", "Test de Velocidad Visual", "Entrenamiento FPS"], fr: ["Test de Temps de Réaction", "Entraînement des Réflexes", "Jeu de Réaction", "Galerie Saccadique", "Suivi des Portes", "Suivi des Barrières", "Test de Suivi Visuel", "Entraînement FPS"] }[locale] || [];
  const base = "https://skilldrills.online";
  const itemList = drillSlugs.map((slug, i) => ({ "@type": "ListItem", position: i + 1, name: names[i] || slug, url: `${base}/drills/reaction-speed/${slug}` }));
  const breadcrumbSchema = { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: ui.breadcrumbHome, item: base }, { "@type": "ListItem", position: 2, name: ui.breadcrumbDrills, item: `${base}/drills` }, { "@type": "ListItem", position: 3, name: ui.breadcrumbCurrent, item: url }] };
  const collectionPageSchema = { "@context": "https://schema.org", "@type": "CollectionPage", name: ui.title, url, description: ui.description, inLanguage: ui.language, isAccessibleForFree: true, author: { "@type": "Organization", name: "SkillDrills", url: base }, mainEntity: { "@type": "ItemList", numberOfItems: itemList.length, itemListElement: itemList } };
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(({ q, a }) => ({ "@type": "Question", name: q, acceptedAnswer: { "@type": "Answer", text: a } })) };
  return { metadata: { title: `${ui.title} | SkillDrills`, description: ui.description, keywords: ui.keywords, robots: { index: true, follow: true }, alternates: { canonical: url, languages }, openGraph: { title: `${ui.title} | SkillDrills`, description: ui.description, url, siteName: "SkillDrills", type: "website", locale: ui.locale, images: [{ url: `${base}/icons/icon-512x512.png`, width: 512, height: 512, alt: ui.title }] }, twitter: { card: "summary_large_image", title: `${ui.title} | SkillDrills`, description: ui.description, images: [`${base}/icons/icon-512x512.png`] } }, breadcrumbSchema, collectionPageSchema, faqSchema };
}
